(function(m){function A(a){var c;return a&&(c=B.exec(a))?(s=c[1],a=c[2].split("/"),t=a.shift(),C="/"+a.join("/"),!0):!1}function J(a){a=a.replace(K,function(a,d){return u[d]||""});if(B.test(a))return a;var c=a.substr(0,1);if("/"==c)return s+"//"+t+a;var b=C.split("/"),d=b.length-1;b[d]="?"==c?b[d]+a:a;return s+"//"+t+b.join("/")}function D(a,c){"array"==g(a)||(a=a.split(L));for(var b=0,d=a.length;b<d;)c(a[b++])}function E(){var a;(a=v.shift())?a(E):n=1}function w(a,c,b){function d(){e--;(f=a.shift())?
f(d):0==e&&c()}var f,e=a.length;if(1>e)return c();for(b||(b=1);0<b--&&(f=a.shift());)f(d)}function i(){if(!F){if(!e.body)return setTimeout(i,1);F=1;n=0;w(v,function(){n=1})}}function p(a,c,b){a=J(a);p[M.test(a)?"link":"script"](a,c,b)}function G(a,c){if(!a)return c();H(a.depends,function(){if(a.state)return c();if(a.test&&("function"==g(a.test)||(a.test=new Function("return ("+a.test+") ? true : false;")),a.test()))return a.state=200,c();a.state=400;var b=[];D(a.assets,function(d){d&&b.push(function(b){p(d,
a.charset,b)})});w(b,function(){a.state=200;c()},3)})}function H(a,c){if(!a)return c();if("object"==g(a))return G(a,c);var b=[];D(a,function(a){if(a){var c=g(a);if("object"!=c){if("string"!=c||!(a in q))throw'component "'+a+'" is not registered';a=q[a]}b.push(function(b){G(a,b)})}});w(b,c)}function h(a,c){if(!x&&!x)if(x=1,"complete"==e.readyState)setTimeout(i,1);else if(e.addEventListener){var b=function(){e.removeEventListener("DOMContentLoaded",b,!1);i()};e.addEventListener("DOMContentLoaded",b,
!1);m.addEventListener("load",i,!1)}else if(e.attachEvent){b=function(){"complete"==e.readyState&&(e.detachEvent("onreadystatechange",b),i())};e.attachEvent("onreadystatechange",b);m.attachEvent("onload",i);var d=!1;try{d=null==m.frameElement}catch(f){}if(d&&e.documentElement.doScroll){var j=function(){try{e.documentElement.doScroll("left")}catch(a){setTimeout(j,1);return}i()};j()}}d=function(b){var d=g(a);if("object"!=d&&"array"!=d&&"string"!=d)throw"argument 'component' must be object or array or string";
H(a,function(){c&&c();b()})};n?(n=0,d(E)):v.push(d)}var e=m.document,k=e.head||e.getElementsByTagName("head")[0]||e.documentElement,L=/[\s|,]+/,B=/^(\w{3,6}:)\/\/([^?]+)/,K=/\{(\w+)\}/g,M=/css$/i,t=location.host,s=location.protocol,C=location.pathname,F=0,n=0,x=0,v=[],N="onload"in e.createElement("link")&&"536"<=(/AppleWebKit\/([\d\.]+)/.exec(navigator.userAgent)||{1:"537"})[1],y=1E4,u={},q={},g,I={},O=Object.prototype.toString,r=0,z="Boolean Number String Function Array Date RegExp Object".split(" "),
l;for(;l=z[r++];)I["[object "+l+"]"]=l.toLowerCase();g=function(a){return null==a?String(a):I[O.call(a)]||"object"};r=k.getElementsByTagName("base");z=r.length;for(l=0;l<z&&!A(r[l++].getAttribute("href")););p.link=function(a,c,b){function d(){j&&clearInterval(j);g&&clearTimeout(g);f=f.onload=null}var f=e.createElement("link"),j=null,g=null;c&&f.setAttribute("charset",c);f.rel="stylesheet";f.href=a;f.type="text/css";N?(f.onload=function(){d();setTimeout(function(){b(200)},0)},f.onerror=function(){b(404)}):
j=setInterval(function(){try{f.sheet.cssRules}catch(a){if(1E3!=a.code&&"security"!=a.message&&"denied"!=a.message)return}d();setTimeout(function(){b(200)},0)},13);g=setTimeout(function(){d();b(404)},y);k.appendChild(f)};p.script=function(a,c,b){var d=e.createElement("script"),f=null,g=function(){f&&clearTimeout(f);d.onload=d.onreadystatechange=d.onerror=null;k&&d.parentNode&&k.removeChild(d);d=null};c&&d.setAttribute("charset",c);d.async="async";d.src=a;d.onload=d.onreadystatechange=function(){if(!d.readyState||
/loaded|complete/.test(d.readyState))g(),setTimeout(function(){b(200)},0)};d.onerror=function(){g();b(404)};f=setTimeout(function(){g();b(404)},y);k.insertBefore(d,k.firstChild)};h.init=function(a){for(var c in a){var b="set"+c.charAt(0).toUpperCase()+c.substr(1);b in h&&h[b](a[c])}};h.setAlias=function(a,c){if("object"==g(a))for(var b in a)u[b]=a[b];else u[a]=c};h.setBase=A;h.setTimeout=function(a){y=parseInt(a)};h.register=function(a,c){if("object"==g(a))for(var b in a)h.register(b,a[b]);else{if(a in
q)throw'component name "'+a+'" is conflict in repos';if("object"!=g(c))throw'argument "conf" must be object';q[a]=c}};m.fet=h})(window);
