(function(){var j=function(a,b){var c=a.style[b];a.currentStyle?c=a.currentStyle[b]:window.getComputedStyle&&(c=document.defaultView.getComputedStyle(a,null).getPropertyValue(b));if("auto"==c&&"cursor"==b)for(var d=["a"],e=0;e<d.length;e++)if(a.tagName.toLowerCase()==d[e])return"pointer";return c},m=function(a){if(e.prototype._singleton){a||(a=window.event);var b;this!==window?b=this:a.target?b=a.target:a.srcElement&&(b=a.srcElement);e.prototype._singleton.setCurrent(b)}},n=function(a,b){if(a.addClass)return a.addClass(b),
a;if(b&&"string"===typeof b){var c=(b||"").split(/\s+/);if(1===a.nodeType)if(a.className){for(var d=" "+a.className+" ",e=a.className,f=0,g=c.length;f<g;f++)0>d.indexOf(" "+c[f]+" ")&&(e+=" "+c[f]);a.className=e.replace(/^\s+|\s+$/g,"")}else a.className=b}return a},k=function(a,b){if(a.removeClass)return a.removeClass(b),a;if(b&&"string"===typeof b||void 0===b){var c=(b||"").split(/\s+/);if(1===a.nodeType&&a.className)if(b){for(var d=(" "+a.className+" ").replace(/[\n\t]/g," "),e=0,f=c.length;e<f;e++)d=
d.replace(" "+c[e]+" "," ");a.className=d.replace(/^\s+|\s+$/g,"")}else a.className=""}return a},p=function(a){return(0<=a.indexOf("?")?"&":"?")+"nocache="+(new Date).getTime()},q=function(a){var b=[];a.trustedDomains&&("string"===typeof a.trustedDomains?b.push("trustedDomain="+a.trustedDomains):b.push("trustedDomain="+a.trustedDomains.join(",")));return b.join("&")},r=function(a,b){if(b.indexOf)return b.indexOf(a);for(var c=0,d=b.length;c<d;c++)if(b[c]===a)return c;return-1},s=function(a){if("string"===
typeof a)throw new TypeError("ZeroClipboard doesn't accept query strings.");return!a.length?[a]:a},e=function(a,b){a&&(e.prototype._singleton||this).glue(a);if(e.prototype._singleton)return e.prototype._singleton;e.prototype._singleton=this;this.options={};for(var c in l)this.options[c]=l[c];for(var d in b)this.options[d]=b[d];this.handlers={};if(e.detectFlashSupport()){c=e.prototype._singleton;d=document.getElementById("global-zeroclipboard-html-bridge");if(!d){var t='      <object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" id="global-zeroclipboard-flash-bridge" width="100%" height="100%">         <param name="movie" value="'+
c.options.moviePath+p(c.options.moviePath)+'"/>         <param name="allowScriptAccess" value="'+c.options.allowScriptAccess+'"/>         <param name="scale" value="exactfit"/>         <param name="loop" value="false"/>         <param name="menu" value="false"/>         <param name="quality" value="best" />         <param name="bgcolor" value="#ffffff"/>         <param name="wmode" value="transparent"/>         <param name="flashvars" value="'+q(c.options)+'"/>         <embed src="'+c.options.moviePath+
p(c.options.moviePath)+'"           loop="false" menu="false"           quality="best" bgcolor="#ffffff"           width="100%" height="100%"           name="global-zeroclipboard-flash-bridge"           allowScriptAccess="always"           allowFullScreen="false"           type="application/x-shockwave-flash"           wmode="transparent"           pluginspage="http://www.macromedia.com/go/getflashplayer"           flashvars="'+q(c.options)+'"           scale="exactfit">         </embed>       </object>';
d=document.createElement("div");d.id="global-zeroclipboard-html-bridge";d.setAttribute("class","global-zeroclipboard-container");d.setAttribute("data-clipboard-ready",!1);d.style.position="absolute";d.style.left="-9999px";d.style.top="-9999px";d.style.width="15px";d.style.height="15px";d.style.zIndex="9999";d.innerHTML=t;document.body.appendChild(d)}c.htmlBridge=d;c.flashBridge=document["global-zeroclipboard-flash-bridge"]||d.children[0].lastElementChild}},i,h=[];e.prototype.setCurrent=function(a){i=
a;this.reposition();a.getAttribute("title")&&this.setTitle(a.getAttribute("title"));this.setHandCursor("pointer"==j(a,"cursor"))};e.prototype.setText=function(a){a&&""!==a&&(this.options.text=a,this.ready()&&this.flashBridge.setText(a))};e.prototype.setTitle=function(a){a&&""!==a&&this.htmlBridge.setAttribute("title",a)};e.prototype.setSize=function(a,b){this.ready()&&this.flashBridge.setSize(a,b)};e.prototype.setHandCursor=function(a){this.ready()&&this.flashBridge.setHandCursor(a)};e.version="1.1.7";
var l={moviePath:"ZeroClipboard.swf",trustedDomains:null,text:null,hoverClass:"zeroclipboard-is-hover",activeClass:"zeroclipboard-is-active",allowScriptAccess:"sameDomain"};e.setDefaults=function(a){for(var b in a)l[b]=a[b]};e.destroy=function(){e.prototype._singleton.unglue(h);var a=e.prototype._singleton.htmlBridge;a.parentNode.removeChild(a);delete e.prototype._singleton};e.detectFlashSupport=function(){var a=!1;try{new ActiveXObject("ShockwaveFlash.ShockwaveFlash")&&(a=!0)}catch(b){navigator.mimeTypes["application/x-shockwave-flash"]&&
(a=!0)}return a};e.prototype.resetBridge=function(){this.htmlBridge.style.left="-9999px";this.htmlBridge.style.top="-9999px";this.htmlBridge.removeAttribute("title");this.htmlBridge.removeAttribute("data-clipboard-text");k(i,this.options.activeClass);i=null;this.options.text=null};e.prototype.ready=function(){var a=this.htmlBridge.getAttribute("data-clipboard-ready");return"true"===a||!0===a};e.prototype.reposition=function(){if(!i)return!1;var a=i,b=0,c=0,d=a.width||a.offsetWidth||0,e=a.height||
a.offsetHeight||0,f=9999,g=j(a,"zIndex");for(g&&"auto"!=g&&(f=parseInt(g,10));a;)var g=parseInt(j(a,"borderLeftWidth"),10),h=parseInt(j(a,"borderTopWidth"),10),b=b+(isNaN(a.offsetLeft)?0:a.offsetLeft),b=b+(isNaN(g)?0:g),c=c+(isNaN(a.offsetTop)?0:a.offsetTop),c=c+(isNaN(h)?0:h),a=a.offsetParent;this.htmlBridge.style.top=c+"px";this.htmlBridge.style.left=b+"px";this.htmlBridge.style.width=d+"px";this.htmlBridge.style.height=e+"px";this.htmlBridge.style.zIndex=f+1;this.setSize(d,e)};e.dispatch=function(a,
b){e.prototype._singleton.receiveEvent(a,b)};e.prototype.on=function(a,b){for(var c=a.toString().split(/\s/g),d=0;d<c.length;d++)a=c[d].toLowerCase().replace(/^on/,""),this.handlers[a]||(this.handlers[a]=b);this.handlers.noflash&&!e.detectFlashSupport()&&this.receiveEvent("onNoFlash",null)};e.prototype.addEventListener=e.prototype.on;e.prototype.off=function(a,b){for(var c=a.toString().split(/\s/g),d=0;d<c.length;d++){var a=c[d].toLowerCase().replace(/^on/,""),e;for(e in this.handlers)e===a&&this.handlers[e]===
b&&delete this.handlers[e]}};e.prototype.removeEventListener=e.prototype.off;e.prototype.receiveEvent=function(a,b){var a=a.toString().toLowerCase().replace(/^on/,""),c=i;switch(a){case "load":if(b&&10>parseFloat(b.flashVersion.replace(",",".").replace(/[^0-9\.]/gi,""))){this.receiveEvent("onWrongFlash",{flashVersion:b.flashVersion});return}this.htmlBridge.setAttribute("data-clipboard-ready",!0);break;case "mouseover":n(c,this.options.hoverClass);break;case "mouseout":k(c,this.options.hoverClass);
this.resetBridge();break;case "mousedown":n(c,this.options.activeClass);break;case "mouseup":k(c,this.options.activeClass);break;case "datarequested":var d=c.getAttribute("data-clipboard-target");(d=(d=!d?null:document.getElementById(d))?d.value||d.textContent||d.innerText:c.getAttribute("data-clipboard-text"))&&this.setText(d);break;case "complete":this.options.text=null}this.handlers[a]&&(d=this.handlers[a],"function"==typeof d?d.call(c,this,b):"string"==typeof d&&window[d].call(c,this,b))};e.prototype.glue=
function(a){for(var a=s(a),b=0;b<a.length;b++)if(-1==r(a[b],h)){h.push(a[b]);var c=a[b],d=m;c.addEventListener?c.addEventListener("mouseover",d,!1):c.attachEvent&&c.attachEvent("onmouseover",d)}};e.prototype.unglue=function(a){for(var a=s(a),b=0;b<a.length;b++){var c=a[b],d=m;c.removeEventListener?c.removeEventListener("mouseover",d,!1):c.detachEvent&&c.detachEvent("onmouseover",d);c=r(a[b],h);-1!=c&&h.splice(c,1)}};"undefined"!==typeof module?module.exports=e:"function"===typeof define&&define.amd?
define(function(){return e}):window.ZeroClipboard=e})();
