document.writeln("<script type=\"text/javascript\">");
document.writeln("/*120*270£¬sqyxqc DL*/");
document.writeln("var cpro_id = \"u1577693\";");
document.writeln("</script>");
document.writeln("<script src=\"http://cpro.baidustatic.com/cpro/ui/f.js\" type=\"text/javascript\"></script>");
document.writeln("");
document.writeln("<script type=\"text/javascript\">");
document.writeln("    /*tu+*/");
document.writeln("var cpro_id = \"u1730634\";");
document.writeln("</script>");
document.writeln("<script src=\"http://cpro.baidustatic.com/cpro/ui/i.js\" type=\"text/javascript\"></script>");
document.writeln("");
document.writeln("<script type=\"text/javascript\">");
document.writeln("    /*250*200*/");
document.writeln("var cpro_id = \"u1754842\";");
document.writeln("</script>");
document.writeln("<script src=\"http://cpro.baidustatic.com/cpro/ui/f.js\" type=\"text/javascript\"></script>");
document.writeln("");