document.writeln("<table><tr><td>");
document.writeln("");
document.writeln("<script type=\"text/javascript\">");
document.writeln("    /*400*200 sqyxqc*/");
document.writeln("    var cpro_id = \"u1759372\";");
document.writeln("</script>");
document.writeln("<script src=\"http://cpro.baidustatic.com/cpro/ui/c.js\" type=\"text/javascript\"></script>");
document.writeln("");
document.writeln("</td><td><div>");
document.writeln("<script type=\"text/javascript\">");
document.writeln("    /*200*200 sq*/");
document.writeln("    var cpro_id = \"u1759375\";");
document.writeln("</script>");
document.writeln("<script src=\"http://cpro.baidustatic.com/cpro/ui/c.js\" type=\"text/javascript\"></script>");
document.writeln("");
document.writeln("</div>");
document.writeln("</td></table>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");