<!DOCTYPE html>
<html>
	<head> <title>COW Proxy</title> </head>
	<body>
		<h1>[Error] read tcp 207.226.142.78:9990: connection reset by peer</h1>
		<p>HTTP Request <strong>GET dtmvdvtzf8rz0.cloudfront.net:80/static/js/pageview.js?version=2.7</strong></p> <p>Parse response from server.</p> <p>Using shadowsocks connection.</p>
		<hr />
		Generated by <i>COW</i> at Thu Dec  4 10:47:13 2014
	</body>
</html>
