(function(){var h={},mt={},c={id:"46db1c7ab0c594c8219d3a3d68e66ff8",dm:["36dsj.com"],js:"tongji.baidu.com/hm-web/js/",etrk:[],icon:'',ctrk:false,align:-1,nv:-1,vdur:1800000,age:31536000000,rec:0,rp:[],trust:0,vcard:0,qiao:0,lxb:0,conv:0,apps:'siteId=2918335&goTop=1'};var p=!0,r=null,s=!1;mt.g={};mt.g.ya=/msie (\d+\.\d+)/i.test(navigator.userAgent);mt.g.cookieEnabled=navigator.cookieEnabled;mt.g.javaEnabled=navigator.javaEnabled();mt.g.language=navigator.language||navigator.browserLanguage||navigator.systemLanguage||navigator.userLanguage||"";mt.g.ka=(window.screen.width||0)+"x"+(window.screen.height||0);mt.g.colorDepth=window.screen.colorDepth||0;mt.cookie={};
mt.cookie.set=function(a,b,d){var e;d.A&&(e=new Date,e.setTime(e.getTime()+d.A));document.cookie=a+"="+b+(d.domain?"; domain="+d.domain:"")+(d.path?"; path="+d.path:"")+(e?"; expires="+e.toGMTString():"")+(d.Ca?"; secure":"")};mt.cookie.get=function(a){return(a=RegExp("(^| )"+a+"=([^;]*)(;|$)").exec(document.cookie))?a[2]:r};mt.event={};mt.event.e=function(a,b,d){a.attachEvent?a.attachEvent("on"+b,function(b){d.call(a,b)}):a.addEventListener&&a.addEventListener(b,d,s)};
mt.event.preventDefault=function(a){a.preventDefault?a.preventDefault():a.returnValue=s};mt.n={};mt.n.parse=function(){return(new Function('return (" + source + ")'))()};
mt.n.stringify=function(){function a(a){/["\\\x00-\x1f]/.test(a)&&(a=a.replace(/["\\\x00-\x1f]/g,function(a){var b=d[a];if(b)return b;b=a.charCodeAt();return"\\u00"+Math.floor(b/16).toString(16)+(b%16).toString(16)}));return'"'+a+'"'}function b(a){return 10>a?"0"+a:a}var d={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"};return function(e){switch(typeof e){case "undefined":return"undefined";case "number":return isFinite(e)?String(e):"null";case "string":return a(e);case "boolean":return String(e);
default:if(e===r)return"null";if(e instanceof Array){var d=["["],n=e.length,l,f,m;for(f=0;f<n;f++)switch(m=e[f],typeof m){case "undefined":case "function":case "unknown":break;default:l&&d.push(","),d.push(mt.n.stringify(m)),l=1}d.push("]");return d.join("")}if(e instanceof Date)return'"'+e.getFullYear()+"-"+b(e.getMonth()+1)+"-"+b(e.getDate())+"T"+b(e.getHours())+":"+b(e.getMinutes())+":"+b(e.getSeconds())+'"';l=["{"];f=mt.n.stringify;for(n in e)if(Object.prototype.hasOwnProperty.call(e,n))switch(m=
e[n],typeof m){case "undefined":case "unknown":case "function":break;default:d&&l.push(","),d=1,l.push(f(n)+":"+f(m))}l.push("}");return l.join("")}}}();mt.lang={};mt.lang.d=function(a,b){return"[object "+b+"]"==={}.toString.call(a)};mt.lang.za=function(a){return mt.lang.d(a,"Number")&&isFinite(a)};mt.lang.Ba=function(a){return mt.lang.d(a,"String")};mt.localStorage={};
mt.localStorage.t=function(){if(!mt.localStorage.f)try{mt.localStorage.f=document.createElement("input"),mt.localStorage.f.type="hidden",mt.localStorage.f.style.display="none",mt.localStorage.f.addBehavior("#default#userData"),document.getElementsByTagName("head")[0].appendChild(mt.localStorage.f)}catch(a){return s}return p};
mt.localStorage.set=function(a,b,d){var e=new Date;e.setTime(e.getTime()+d||31536E6);try{window.localStorage?(b=e.getTime()+"|"+b,window.localStorage.setItem(a,b)):mt.localStorage.t()&&(mt.localStorage.f.expires=e.toUTCString(),mt.localStorage.f.load(document.location.hostname),mt.localStorage.f.setAttribute(a,b),mt.localStorage.f.save(document.location.hostname))}catch(k){}};
mt.localStorage.get=function(a){if(window.localStorage){if(a=window.localStorage.getItem(a)){var b=a.indexOf("|"),d=a.substring(0,b)-0;if(d&&d>(new Date).getTime())return a.substring(b+1)}}else if(mt.localStorage.t())try{return mt.localStorage.f.load(document.location.hostname),mt.localStorage.f.getAttribute(a)}catch(e){}return r};
mt.localStorage.remove=function(a){if(window.localStorage)window.localStorage.removeItem(a);else if(mt.localStorage.t())try{mt.localStorage.f.load(document.location.hostname),mt.localStorage.f.removeAttribute(a),mt.localStorage.f.save(document.location.hostname)}catch(b){}};mt.sessionStorage={};mt.sessionStorage.set=function(a,b){if(window.sessionStorage)try{window.sessionStorage.setItem(a,b)}catch(d){}};
mt.sessionStorage.get=function(a){return window.sessionStorage?window.sessionStorage.getItem(a):r};mt.sessionStorage.remove=function(a){window.sessionStorage&&window.sessionStorage.removeItem(a)};mt.H={};mt.H.log=function(a,b){var d=new Image,e="mini_tangram_log_"+Math.floor(2147483648*Math.random()).toString(36);window[e]=d;d.onload=d.onerror=d.onabort=function(){d.onload=d.onerror=d.onabort=r;d=window[e]=r;b&&b(a)};d.src=a};mt.I={};
mt.I.ca=function(){var a="";if(navigator.plugins&&navigator.mimeTypes.length){var b=navigator.plugins["Shockwave Flash"];b&&b.description&&(a=b.description.replace(/^.*\s+(\S+)\s+\S+$/,"$1"))}else if(window.ActiveXObject)try{if(b=new ActiveXObject("ShockwaveFlash.ShockwaveFlash"))(a=b.GetVariable("$version"))&&(a=a.replace(/^.*\s+(\d+),(\d+).*$/,"$1.$2"))}catch(d){}return a};
mt.I.ua=function(a,b,d,e,k){return'<object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" id="'+a+'" width="'+d+'" height="'+e+'"><param name="movie" value="'+b+'" /><param name="flashvars" value="'+(k||"")+'" /><param name="allowscriptaccess" value="always" /><embed type="application/x-shockwave-flash" name="'+a+'" width="'+d+'" height="'+e+'" src="'+b+'" flashvars="'+(k||"")+'" allowscriptaccess="always" /></object>'};mt.url={};
mt.url.l=function(a,b){var d=a.match(RegExp("(^|&|\\?|#)("+b+")=([^&#]*)(&|$|#)",""));return d?d[3]:r};mt.url.wa=function(a){return(a=a.match(/^(https?:)\/\//))?a[1]:r};mt.url.$=function(a){return(a=a.match(/^(https?:\/\/)?([^\/\?#]*)/))?a[2].replace(/.*@/,""):r};mt.url.K=function(a){return(a=mt.url.$(a))?a.replace(/:\d+$/,""):a};mt.url.va=function(a){return(a=a.match(/^(https?:\/\/)?[^\/]*(.*)/))?a[2].replace(/[\?#].*/,"").replace(/^$/,"/"):r};
h.k={xa:"http://tongji.baidu.com/hm-web/welcome/ico",P:"hm.baidu.com/hm.gif",S:"baidu.com",fa:"hmmd",ga:"hmpl",ea:"hmkw",da:"hmci",ha:"hmsr",m:0,h:Math.round(+new Date/1E3),protocol:"https:"==document.location.protocol?"https:":"http:",Aa:0,ra:6E5,sa:10,ta:1024,qa:1,r:2147483647,Q:"bs cc cf ci ck cl cm cp cw ds ep et fl ja ln lo lt nv rnd si st su v cv lv api tt u".split(" ")};
(function(){var a={i:{},e:function(a,d){this.i[a]=this.i[a]||[];this.i[a].push(d)},p:function(a,d){this.i[a]=this.i[a]||[];for(var e=this.i[a].length,k=0;k<e;k++)this.i[a][k](d)}};return h.z=a})();
(function(){function a(a,e){var k=document.createElement("script");k.charset="utf-8";b.d(e,"Function")&&(k.readyState?k.onreadystatechange=function(){if("loaded"===k.readyState||"complete"===k.readyState)k.onreadystatechange=r,e()}:k.onload=function(){e()});k.src=a;var n=document.getElementsByTagName("script")[0];n.parentNode.insertBefore(k,n)}var b=mt.lang;return h.load=a})();
(function(){var a=function(){var a=navigator.userAgent.toLowerCase();if(0<=a.indexOf("chrome")){var d;d=(a=a.match(/chrome\/(\d+)/))?a[1]:-1;var e=window.document,a="track"in e.createElement("track"),e="scoped"in e.createElement("style"),k="v8Locale"in window,n=document.createElement("canvas"),l="seamless"in document.createElement("iframe"),f=s;try{n.getContext("webgl")&&(f=p)}catch(m){}if(!f&&"31"===d)return 1;if(!(d=(l||!f)&&"38"===d))if(d=a)if(d=!e)if(d=!k){var g;a:{d=window.navigator.mimeTypes;
for(g in d)if("application/vnd.chromium.remoting-viewer"===d[g].type){g=p;break a}g=s}d=!g}if(d)return 7;if(a&&e&&k)return 1}return-1}();return h.U=a})();
(function(){function a(){return function(){h.b.a.nv=0;h.b.a.st=4;h.b.a.et=3;h.b.a.ep=h.w.aa()+","+h.w.Z();h.b.j()}}function b(){clearTimeout(A);var a;y&&(a="visible"==document[y]);B&&(a=!document[B]);f="undefined"==typeof a?p:a;if((!l||!m)&&f&&g)t=p,u=+new Date;else if(l&&m&&(!f||!g))t=s,q+=+new Date-u;l=f;m=g;A=setTimeout(b,100)}function d(a){var m=document,q="";if(a in m)q=a;else for(var t=["webkit","ms","moz","o"],g=0;g<t.length;g++){var b=t[g]+a.charAt(0).toUpperCase()+a.slice(1);if(b in m){q=
b;break}}return q}function e(a){if(!("focus"==a.type||"blur"==a.type)||!(a.target&&a.target!=window))g="focus"==a.type||"focusin"==a.type?p:s,b()}var k=mt.event,n=h.z,l=p,f=p,m=p,g=p,w=+new Date,u=w,q=0,t=p,y=d("visibilityState"),B=d("hidden"),A;b();(function(){var a=y.replace(/[vV]isibilityState/,"visibilitychange");k.e(document,a,b);k.e(window,"pageshow",b);k.e(window,"pagehide",b);"object"==typeof document.onfocusin?(k.e(document,"focusin",e),k.e(document,"focusout",e)):(k.e(window,"focus",e),
k.e(window,"blur",e))})();h.w={aa:function(){return+new Date-w},Z:function(){return t?+new Date-u+q:q}};n.e("pv-b",function(){k.e(window,"unload",a())});return h.w})();
(function(){function a(m){for(var g in m)if({}.hasOwnProperty.call(m,g)){var b=m[g];e.d(b,"Object")||e.d(b,"Array")?a(b):m[g]=String(b)}}function b(a){return a.replace?a.replace(/'/g,"'0").replace(/\*/g,"'1").replace(/!/g,"'2"):a}var d=mt.H,e=mt.lang,k=mt.n,n=h.k,l=h.z,f={L:r,o:[],s:0,M:s,init:function(){f.c=0;f.L={push:function(){f.F.apply(f,arguments)}};l.e("pv-b",function(){f.W();f.X()});l.e("pv-d",f.Y);l.e("stag-b",function(){h.b.a.api=f.c||f.s?f.c+"_"+f.s:""});l.e("stag-d",function(){h.b.a.api=
0;f.c=0;f.s=0})},W:function(){var a=window._hmt;if(a&&a.length)for(var b=0;b<a.length;b++){var d=a[b];switch(d[0]){case "_setAccount":1<d.length&&/^[0-9a-z]{32}$/.test(d[1])&&(f.c|=1,window._bdhm_account=d[1]);break;case "_setAutoPageview":if(1<d.length&&(d=d[1],s===d||p===d))f.c|=2,window._bdhm_autoPageview=d}}},X:function(){if("undefined"===typeof window._bdhm_account||window._bdhm_account===c.id){window._bdhm_account=c.id;var a=window._hmt;if(a&&a.length)for(var b=0,d=a.length;b<d;b++)e.d(a[b],
"Array")&&"_trackEvent"!==a[b][0]&&"_trackRTEvent"!==a[b][0]?f.F(a[b]):f.o.push(a[b]);window._hmt=f.L}},Y:function(){if(0<f.o.length)for(var a=0,b=f.o.length;a<b;a++)f.F(f.o[a]);f.o=r},F:function(a){if(e.d(a,"Array")){var b=a[0];if(f.hasOwnProperty(b)&&e.d(f[b],"Function"))f[b](a)}},_trackPageview:function(a){if(1<a.length&&a[1].charAt&&"/"==a[1].charAt(0)){f.c|=4;h.b.a.et=0;h.b.a.ep="";h.b.C?(h.b.a.nv=0,h.b.a.st=4):h.b.C=p;var b=h.b.a.u,d=h.b.a.su;h.b.a.u=n.protocol+"//"+document.location.host+a[1];
f.M||(h.b.a.su=document.location.href);h.b.j();h.b.a.u=b;h.b.a.su=d}},_trackEvent:function(a){2<a.length&&(f.c|=8,h.b.a.nv=0,h.b.a.st=4,h.b.a.et=4,h.b.a.ep=b(a[1])+"*"+b(a[2])+(a[3]?"*"+b(a[3]):"")+(a[4]?"*"+b(a[4]):""),h.b.j())},_setCustomVar:function(a){if(!(4>a.length)){var d=a[1],e=a[4]||3;if(0<d&&6>d&&0<e&&4>e){f.s++;for(var k=(h.b.a.cv||"*").split("!"),q=k.length;q<d-1;q++)k.push("*");k[d-1]=e+"*"+b(a[2])+"*"+b(a[3]);h.b.a.cv=k.join("!");a=h.b.a.cv.replace(/[^1](\*[^!]*){2}/g,"*").replace(/((^|!)\*)+$/g,
"");""!==a?h.b.setData("Hm_cv_"+c.id,encodeURIComponent(a),c.age):h.b.ia("Hm_cv_"+c.id)}}},_setReferrerOverride:function(a){1<a.length&&(h.b.a.su=a[1].charAt&&"/"==a[1].charAt(0)?n.protocol+"//"+window.location.host+a[1]:a[1],f.M=p)},_trackOrder:function(b){b=b[1];e.d(b,"Object")&&(a(b),f.c|=16,h.b.a.nv=0,h.b.a.st=4,h.b.a.et=94,h.b.a.ep=k.stringify(b),h.b.j())},_trackMobConv:function(a){if(a={webim:1,tel:2,map:3,sms:4,callback:5,share:6}[a[1]])f.c|=32,h.b.a.et=93,h.b.a.ep=a,h.b.j()},_trackRTPageview:function(b){b=
b[1];e.d(b,"Object")&&(a(b),b=k.stringify(b),512>=encodeURIComponent(b).length&&(f.c|=64,h.b.a.rt=b))},_trackRTEvent:function(b){b=b[1];if(e.d(b,"Object")){a(b);b=encodeURIComponent(k.stringify(b));var d=function(a){var b=h.b.a.rt;f.c|=128;h.b.a.et=90;h.b.a.rt=a;h.b.j();h.b.a.rt=b},l=b.length;if(900>=l)d.call(this,b);else for(var l=Math.ceil(l/900),u="block|"+Math.round(Math.random()*n.r).toString(16)+"|"+l+"|",q=[],t=0;t<l;t++)q.push(t),q.push(b.substring(900*t,900*t+900)),d.call(this,u+q.join("|")),
q=[]}},_setUserId:function(a){a=a[1];if(e.d(a,"String")||e.d(a,"Number")){var b=h.b.B(),k="hm-"+h.b.a.v;f.O=f.O||Math.round(Math.random()*n.r);d.log("//datax.baidu.com/x.gif?si="+c.id+"&dm="+encodeURIComponent(b)+"&ac="+encodeURIComponent(a)+"&v="+k+"&li="+f.O+"&rnd="+Math.round(Math.random()*n.r))}}};f.init();h.T=f;return h.T})();
(function(){function a(){"undefined"==typeof window["_bdhm_loaded_"+c.id]&&(window["_bdhm_loaded_"+c.id]=p,this.a={},this.C=s,this.init())}var b=mt.url,d=mt.H,e=mt.I,k=mt.lang,n=mt.cookie,l=mt.g,f=mt.localStorage,m=mt.sessionStorage,g=h.k,w=h.U,u=h.z;a.prototype={D:function(a,b){a="."+a.replace(/:\d+/,"");b="."+b.replace(/:\d+/,"");var d=a.indexOf(b);return-1<d&&d+b.length==a.length},N:function(a,b){a=a.replace(/^https?:\/\//,"");return 0===a.indexOf(b)},q:function(a){for(var d=0;d<c.dm.length;d++)if(-1<
c.dm[d].indexOf("/")){if(this.N(a,c.dm[d]))return p}else{var e=b.K(a);if(e&&this.D(e,c.dm[d]))return p}return s},B:function(){for(var a=document.location.hostname,b=0,d=c.dm.length;b<d;b++)if(this.D(a,c.dm[b]))return c.dm[b].replace(/(:\d+)?[\/\?#].*/,"");return a},J:function(){for(var a=0,b=c.dm.length;a<b;a++){var d=c.dm[a];if(-1<d.indexOf("/")&&this.N(document.location.href,d))return d.replace(/^[^\/]+(\/.*)/,"$1")+"/"}return"/"},ba:function(){if(!document.referrer)return g.h-g.m>c.vdur?1:4;var a=
s;this.q(document.referrer)&&this.q(document.location.href)?a=p:(a=b.K(document.referrer),a=this.D(a||"",document.location.hostname));return a?g.h-g.m>c.vdur?1:4:3},getData:function(a){try{return n.get(a)||m.get(a)||f.get(a)}catch(b){}},setData:function(a,b,d){try{n.set(a,b,{domain:this.B(),path:this.J(),A:d}),d?f.set(a,b,d):m.set(a,b)}catch(e){}},ia:function(a){try{n.set(a,"",{domain:this.B(),path:this.J(),A:-1}),m.remove(a),f.remove(a)}catch(b){}},oa:function(){var a,b,d,e,f;g.m=this.getData("Hm_lpvt_"+
c.id)||0;13==g.m.length&&(g.m=Math.round(g.m/1E3));b=this.ba();a=4!=b?1:0;if(d=this.getData("Hm_lvt_"+c.id)){e=d.split(",");for(f=e.length-1;0<=f;f--)13==e[f].length&&(e[f]=""+Math.round(e[f]/1E3));for(;2592E3<g.h-e[0];)e.shift();f=4>e.length?2:3;for(1===a&&e.push(g.h);4<e.length;)e.shift();d=e.join(",");e=e[e.length-1]}else d=g.h,e="",f=1;this.setData("Hm_lvt_"+c.id,d,c.age);this.setData("Hm_lpvt_"+c.id,g.h);d=g.h==this.getData("Hm_lpvt_"+c.id)?"1":"0";if(0===c.nv&&this.q(document.location.href)&&
(""===document.referrer||this.q(document.referrer)))a=0,b=4;this.a.nv=a;this.a.st=b;this.a.cc=d;this.a.lt=e;this.a.lv=f},na:function(){for(var a=[],b=0,d=g.Q.length;b<d;b++){var e=g.Q[b],f=this.a[e];"undefined"!=typeof f&&""!==f&&a.push(e+"="+encodeURIComponent(f))}b=this.a.et;this.a.rt&&(0===b?a.push("rt="+encodeURIComponent(this.a.rt)):90===b&&a.push("rt="+this.a.rt));return a.join("&")},pa:function(){this.oa();this.a.si=c.id;this.a.su=document.referrer;this.a.ds=l.ka;this.a.cl=l.colorDepth+"-bit";
this.a.ln=l.language;this.a.ja=l.javaEnabled?1:0;this.a.ck=l.cookieEnabled?1:0;this.a.bs=w;this.a.lo="number"==typeof _bdhm_top?1:0;this.a.fl=e.ca();this.a.v="1.0.72";this.a.cv=decodeURIComponent(this.getData("Hm_cv_"+c.id)||"");1==this.a.nv&&(this.a.tt=document.title||"");var a=document.location.href;this.a.cm=b.l(a,g.fa)||"";this.a.cp=b.l(a,g.ga)||"";this.a.cw=b.l(a,g.ea)||"";this.a.ci=b.l(a,g.da)||"";this.a.cf=b.l(a,g.ha)||""},init:function(){try{this.pa(),0===this.a.nv?this.ma():this.G(".*"),
h.b=this,this.V(),u.p("pv-b"),this.la()}catch(a){var b=[];b.push("si="+c.id);b.push("n="+encodeURIComponent(a.name));b.push("m="+encodeURIComponent(a.message));b.push("r="+encodeURIComponent(document.referrer));d.log(g.protocol+"//"+g.P+"?"+b.join("&"))}},la:function(){function a(){u.p("pv-d")}"undefined"===typeof window._bdhm_autoPageview||window._bdhm_autoPageview===p?(this.C=p,this.a.et=0,this.a.ep="",this.j(a)):a()},j:function(a){var b=this;b.a.rnd=Math.round(Math.random()*g.r);u.p("stag-b");
var e=g.protocol+"//"+g.P+"?"+b.na();u.p("stag-d");b.R(e);d.log(e,function(d){b.G(d);k.d(a,"Function")&&a.call(b)})},V:function(){var a=document.location.hash.substring(1),d=RegExp(c.id),e=-1<document.referrer.indexOf(g.S)?p:s,f=b.l(a,"jn"),k=/^heatlink$|^select$/.test(f);a&&(d.test(a)&&e&&k)&&(a=document.createElement("script"),a.setAttribute("type","text/javascript"),a.setAttribute("charset","utf-8"),a.setAttribute("src",g.protocol+"//"+c.js+f+".js?"+this.a.rnd),f=document.getElementsByTagName("script")[0],
f.parentNode.insertBefore(a,f))},R:function(a){var b=m.get("Hm_unsent_"+c.id)||"",d=this.a.u?"":"&u="+encodeURIComponent(document.location.href),b=encodeURIComponent(a.replace(/^https?:\/\//,"")+d)+(b?","+b:"");m.set("Hm_unsent_"+c.id,b)},G:function(a){var b=m.get("Hm_unsent_"+c.id)||"";b&&((b=b.replace(RegExp(encodeURIComponent(a.replace(/^https?:\/\//,"")).replace(/([\*\(\)])/g,"\\$1")+"(%26u%3D[^,]*)?,?","g"),"").replace(/,$/,""))?m.set("Hm_unsent_"+c.id,b):m.remove("Hm_unsent_"+c.id))},ma:function(){var a=
this,b=m.get("Hm_unsent_"+c.id);if(b)for(var b=b.split(","),e=function(b){d.log(g.protocol+"//"+decodeURIComponent(b).replace(/^https?:\/\//,""),function(b){a.G(b)})},f=0,k=b.length;f<k;f++)e(b[f])}};return new a})();var v=h.k,x=h.load;if(c.apps){var z=[v.protocol,"//ers.baidu.com/app/s.js?"];z.push(c.apps);x(z.join(""))}var C=h.k,D=h.load;if(c.conv&&"http:"===C.protocol){var E=["http://page.baidu.com/conversion_js.php?sid="];E.push(c.conv);D(E.join(""))}var F=h.k,G=h.load;
c.lxb&&G([F.protocol,"//lxbjs.baidu.com/lxb.js?sid=",c.lxb].join(""));var H=h.load,I=h.k.protocol;if(c.qiao){var J=[I];J.push("http:"===I?"//qiao.baidu.com/site/":"//rqiao.baidu.com/site/");for(var K=c.id,L=5381,M=K.length,N=0;N<M;N++)L=(33*L+Number(K.charCodeAt(N)))%4294967296;2147483648<L&&(L-=2147483648);J.push(L%1E3+"/");J.push(c.id+"/b.js");H(J.join(""))};})();
