(function(a,b){function c(a){this.config=a;this.init()}c.prototype.init=function(){this.modalId=this.config.modalElementId;this.contentLoaded=!1;this.iFrameElement=this.fromSource=this.fromType=this.modalMessages=null;b.event.trigger("modalSignupLoaded");this.initModal();this.bindTriggers();this.bindEvents();a.registerMessageReceiver(b.proxy(this.messageReceiver,this))};c.prototype.initModal=function(){var a;a=null!==window.location.href.match("/upload")?b('a[href*="/login?"], a[href$="/login"],a[href*="/signup?"], a[href$="/signup"], a[href*="/upload?"],a[href$="/upload"]').filter(":not(.void_fancybox, .smt-link)"):
b('a[href*="/login?"], a[href$="/login"],a[href*="/signup?"], a[href$="/signup"], button[href*="/signup"]').filter(":not(.void_fancybox, .smt-link)");a.attr("data-toggle","modal");a.attr("data-target","#"+this.modalId);b("body").append('<div class="modal fade FBlogin login-wrapper hide" id="'+this.modalId+'" style="width:470px;height:347px;"></div>');this.modalElement=b("#"+this.modalId)};c.prototype.appendHeader=function(){this.modalMessages||(this.modalMessages={download:"to download...",addcontact:"to follow...",
favorite:"to like...",comments:"to post a comment...",AddToCommunity:"to add this document to a group/event...",follow:"to follow this user...",business:"to continue...",upload:"to start uploading...",contest:"to vote...",rsvp:"to join this meeting...",user:"to register the username...",zipcast:"to schedule a meeting...",create:"to start creating...",_end:""});this.fromType&&("undefined"!==typeof this.modalMessages[this.fromType]&&1<this.modalMessages[this.fromType].length)&&(b("#modal-login-heading").children("span").remove(),
b("#modal-login-heading").append("<span>"+this.modalMessages[this.fromType]+this.modalMessages._end+"</span>"))};c.prototype.bindTriggers=function(){b(document).on("click","a[data-toggle=modal], button[data-toggle=modal]",b.proxy(function(a){var c=b(a.currentTarget);(href=c.attr("href"))&&0<href.length||(href=c.data("href"));typeof a.currentTarget&&(a.currentTarget&&href&&0<href.length&&!c.hasClass("j-pro-hero-slideshow"))&&(a.preventDefault(),this.open(href,c.attr("data-target")))},this))};c.prototype.bindEvents=
function(){b(".modal-header .close").on("click",b.proxy(this.closedHandler,this));b("#fb-login-modalbox").on("click",function(){a.ga("Signup","fancybox_fblogin_clicked")})};c.prototype.messageReceiver=function(a){switch(a){case "Signup_show_from_iframe":b("#j-facebook-text span").text("connect");b("#modal-login-heading").html("Signup for SlideShare ");this.appendHeader();b(".btn-fb-modal").show();slideshare_object.ga("Signup","Signup_loaded");break;case "login_show_from_iframe":b("#j-facebook-text span").text("login");
b("#modal-login-heading").html("Login to SlideShare ");this.appendHeader();slideshare_object.ga("Signup","Login_clicked");break;case "modalLoginSubmit":this.modalLoginCallBack();break;case "hideSpinner":b(".spinnerForIframe").hide();b("#j-fb-modal-btn").show();b("#modal_login_iframe").show();break;case "toggle_fb_message":a=b(".btn-fb-modal, .btn-fb-modal-other, .btn-fb-modal-de"),a.is(":visible")?a.fadeOut(200):a.fadeIn(500)}};c.prototype.open=function(c,g){this.openModal();this.url=c.replace("/login?",
"/account/render_iframe_login?");this.url=c.replace("/signup?","/account/render_iframe_login?");this.url=c||"/account/render_iframe_login";g=g||"#"+this.modalId;this.fromType=getUrlVar("from",c);this.fromSource=getUrlVar("from_source",c);!1===this.contentLoaded?(b(g).load(c,b.proxy(this.appendHeader,this)),this.contentLoaded=!0):this.appendHeader();a.ga("Signup","thickbox_loaded")};c.prototype.openModal=function(){b("#"+this.modalId).modal("show")};c.prototype.closedHandler=function(){a.isDownloadUrl(this.url)?
a.ga("Signup","thickbox_closed","download"):a.ga("Signup","thickbox_closed");return!0};c.prototype.modalLoginCallBack=function(){a.isDownloadUrl(this.url)?a.ga("Login","ss_login","ss_login_from_fancybox(download)"):a.ga("Login","ss_login","ss_login_from_fancybox");if(!0===window.location.pathname.startsWith("/upload")&&(a.ga("Upload","ss_login_successful"),/loggedout_/.test(window.location.href)))return window.location.replace(window.location.href.replace("loggedout_","loggedin_loggedout_")),!1;var b=
-1!==jQuery.inArray(this.fromType,["business","upload","download","favorite"]),c=decodeURIComponent(this.fromSource);b&&this.fromSource&&1<this.fromSource.length&&isInternalRedirect(this.fromSource)&&window.location.href!==c?window.location.href=c:window.location.reload()};"undefined"!==typeof Foundation&&(c.prototype.initModal=function(){b("body").append('<div class="modal-login-wrapper reveal-modal" id="'+this.modalId+'" data-reveal></div>');this.modalElement=b("#"+this.modalId)},c.prototype.bindTriggers=
function(){b(document).on("click","a[data-reveal-id="+this.modalId+"], button[data-reveal-id="+this.modalId+"]",b.proxy(function(c){if(!a.user||!a.user.loggedin){var g=b(c.currentTarget);if(c.currentTarget&&(href=g.attr("href"))&&0<href.length)c.preventDefault(),this.open(href,g.attr("reveal-id"))}},this))},c.prototype.bindEvents=function(){b(document).on("closed.fndtn.reveal",this.modalElement,b.proxy(this.closedHandler,this))},c.prototype.messageReceiver=function(a){switch(a){case "Signup_show_from_iframe":b("#modal-login-heading").html("Signup for SlideShare ");
this.appendHeader();slideshare_object.ga("Signup","Signup_loaded");break;case "login_show_from_iframe":b("#modal-login-heading").html("Login to SlideShare ");this.appendHeader();slideshare_object.ga("Signup","Login_clicked");break;case "fbconnectNewUser":case "fbconnectExistingUser":window.location.replace("/fbconnect/landingpage?from="+this.fromSource);break;case "fbconnectExistingUserWithLinkedAccount":var a=getUrlVar("from",this.url),c=decodeURIComponent(this.fromSource);void 0!==getUrlVars(this.fromSource).from_logout&&
"undefined"==typeof a?window.location.replace("/?ss"):window.location.pathname.startsWith("/upload")&&/loggedout_/.test(window.location.href)?window.location.replace(window.location.href.replace("loggedout_","loggedin_loggedout_")):isInternalRedirect(this.fromSource)&&window.location.href!==c?window.location.href=decodeURIComponent(this.fromSource):window.location.reload();break;case "fbconnectFailed":this.closeModal();break;case "fbconnectSuspendedUser":this.closeModal();break;case "fbconnectDefault":window.location.reload();
break;case "modalLoginSubmit":this.modalLoginCallBack();break;case "hideSpinner":b(".frame-loading").hide();break;case "forgotPassword":window.location.href=b("#forgot-password-url").val()}},c.prototype.openModal=function(){this.modalElement.foundation("reveal","open")},c.prototype.closeModal=function(){this.modalElement.foundation("reveal","close")});b(document).ready(function(){if(!a.user.loggedin){var b=new c({iFrameSelector:"#modal_login_iframe",modalElementId:"login_modal"});window.initiate_login_modal=
function(a,c){b.open(a,c)}}});window.initiate_login_modal=function(){error("Login modal initialization cannot be performed")}})(slideshare_object,jQuery);
(function(a,b){a.events_queue=[];a.track_time=[];a.event_tracking_url="track.slideshare.net/event";a.setup_event_tracking=function(){a.sendPendingEvents=function(){for(var a=JSON.parse(localStorage.getItem("event"))||[];a.length;){var b=a.pop();slideshare_object.send_events(b)}localStorage.setItem("event",JSON.stringify(a))};a.push_events=function(b,d,g){a.events_queue=JSON.parse(localStorage.getItem("event"))||[];var f=(new Date).getTime();a.events_queue.push({app_name:"Slideshare",event_name:b,
time:f,entity:d,metadata:g});localStorage.setItem("event",JSON.stringify(a.events_queue))};a.push_event_instantly=function(b,d,g){var f=(new Date).getTime();a.send_events({app_name:"Slideshare",event_name:b,time:f,entity:d,metadata:g})};a.send_events=function(c){/slideshare\.net/.test(window.location.hostname)&&b.ajax({url:document.location.protocol+"//"+a.event_tracking_url,type:"post",beforeSend:function(a){a.setRequestHeader("Accept","application/json");a.setRequestHeader("Cookie",document.cookie)},
data:JSON.stringify(c),dataType:"json",async:!0,xhrFields:{withCredentials:!0}})}}})(slideshare_object,jQuery);$(function(){slideshare_object.setup_event_tracking()});$(document).ready(function(){slideshare_object.sendPendingEvents()});
(function(a){a(["jquery"],function(a){function c(c){return a.isFunction(c)||a.isPlainObject(c)?c:{top:c,left:c}}var d=a.scrollTo=function(c,d,e){return a(window).scrollTo(c,d,e)};d.defaults={axis:"xy",duration:0,limit:!0};d.window=function(){return a(window)._scrollable()};a.fn._scrollable=function(){return this.map(function(){if(this.nodeName&&-1==a.inArray(this.nodeName.toLowerCase(),["iframe","#document","html","body"]))return this;var c=(this.contentWindow||this).document||this.ownerDocument||
this;return/webkit/i.test(navigator.userAgent)||"BackCompat"==c.compatMode?c.body:c.documentElement})};a.fn.scrollTo=function(g,f,e){"object"==typeof f&&(e=f,f=0);"function"==typeof e&&(e={onAfter:e});"max"==g&&(g=9E9);e=a.extend({},d.defaults,e);f=f||e.duration;e.queue=e.queue&&1<e.axis.length;e.queue&&(f/=2);e.offset=c(e.offset);e.over=c(e.over);return this._scrollable().each(function(){function i(a){h.animate(m,f,e.easing,a&&function(){a.call(this,p,e)})}if(null!=g){var j=this,h=a(j),p=g,w,m={},
r=h.is("html,body");switch(typeof p){case "number":case "string":if(/^([+-]=?)?\d+(\.\d+)?(px|%)?$/.test(p)){p=c(p);break}p=r?a(p):a(p,this);if(!p.length)return;case "object":if(p.is||p.style)w=(p=a(p)).offset()}var F=a.isFunction(e.offset)&&e.offset(j,p)||e.offset;a.each(e.axis.split(""),function(a,b){var c="x"==b?"Left":"Top",g=c.toLowerCase(),f="scroll"+c,y=j[f],z=d.max(j,b);w?(m[f]=w[g]+(r?0:y-h.offset()[g]),e.margin&&(m[f]-=parseInt(p.css("margin"+c))||0,m[f]-=parseInt(p.css("border"+c+"Width"))||
0),m[f]+=F[g]||0,e.over[g]&&(m[f]+=p["x"==b?"width":"height"]()*e.over[g])):(c=p[g],m[f]=c.slice&&"%"==c.slice(-1)?parseFloat(c)/100*z:c);e.limit&&/^\d+$/.test(m[f])&&(m[f]=0>=m[f]?0:Math.min(m[f],z));!a&&e.queue&&(y!=m[f]&&i(e.onAfterFirst),delete m[f])});i(e.onAfter)}}).end()};d.max=function(c,d){var e="x"==d?"Width":"Height",i="scroll"+e;if(!a(c).is("html,body"))return c[i]-a(c)[e.toLowerCase()]();var e="client"+e,j=c.ownerDocument.documentElement,h=c.ownerDocument.body;return Math.max(j[i],h[i])-
Math.min(j[e],h[e])};return d})})("function"===typeof define&&define.amd?define:function(a,b){"undefined"!==typeof module&&module.exports?module.exports=b(require("jquery")):b(jQuery)});
!function(a,b,c,d){var g=a(b);a.fn.lazyload=function(f){function e(){var b=0;j.each(function(){var c=a(this);if((!h.skip_invisible||c.is(":visible"))&&!a.abovethetop(this,h)&&!a.leftofbegin(this,h))if(a.belowthefold(this,h)||a.rightoffold(this,h)){if(++b>h.failure_limit)return!1}else c.trigger("appear"),b=0})}var i,j=this,h={threshold:0,failure_limit:0,event:"scroll",effect:"show",container:b,data_attribute:"original",skip_invisible:!0,appear:null,load:null,placeholder:"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsQAAA7EAZUrDhsAAAANSURBVBhXYzh8+PB/AAffA0nNPuCLAAAAAElFTkSuQmCC"};
return f&&(d!==f.failurelimit&&(f.failure_limit=f.failurelimit,delete f.failurelimit),d!==f.effectspeed&&(f.effect_speed=f.effectspeed,delete f.effectspeed),a.extend(h,f)),i=h.container===d||h.container===b?g:a(h.container),0===h.event.indexOf("scroll")&&i.bind(h.event,function(){return e()}),this.each(function(){var b=this,c=a(b);b.loaded=!1;(c.attr("src")===d||!1===c.attr("src"))&&c.attr("src",h.placeholder);c.one("appear",function(){this.loaded||(h.appear&&h.appear.call(b,j.length,h),a("<img />").bind("load",
function(){var d=c.data(h.data_attribute);c.hide();c.is("img")?c.attr("src",d):c.css("background-image","url('"+d+"')");c[h.effect](h.effect_speed);b.loaded=!0;d=a.grep(j,function(a){return!a.loaded});(j=a(d),h.load)&&h.load.call(b,j.length,h)}).attr("src",c.data(h.data_attribute)))});0!==h.event.indexOf("scroll")&&c.bind(h.event,function(){b.loaded||c.trigger("appear")})}),g.bind("resize",function(){e()}),/iphone|ipod|ipad.*os 5/gi.test(navigator.appVersion)&&g.bind("pageshow",function(b){b.originalEvent&&
b.originalEvent.persisted&&j.each(function(){a(this).trigger("appear")})}),a(c).ready(function(){e()}),this};a.belowthefold=function(c,e){var i;return i=e.container===d||e.container===b?(b.innerHeight?b.innerHeight:g.height())+g.scrollTop():a(e.container).offset().top+a(e.container).height(),i<=a(c).offset().top-e.threshold};a.rightoffold=function(c,e){var i;return i=e.container===d||e.container===b?g.width()+g.scrollLeft():a(e.container).offset().left+a(e.container).width(),i<=a(c).offset().left-
e.threshold};a.abovethetop=function(c,e){var i;return i=e.container===d||e.container===b?g.scrollTop():a(e.container).offset().top,i>=a(c).offset().top+e.threshold+a(c).height()};a.leftofbegin=function(c,e){var i;return i=e.container===d||e.container===b?g.scrollLeft():a(e.container).offset().left,i>=a(c).offset().left+e.threshold+a(c).width()};a.inviewport=function(b,c){return!(a.rightoffold(b,c)||a.leftofbegin(b,c)||a.belowthefold(b,c)||a.abovethetop(b,c))};a.extend(a.expr[":"],{"below-the-fold":function(b){return a.belowthefold(b,
{threshold:0})},"above-the-top":function(b){return!a.belowthefold(b,{threshold:0})},"right-of-screen":function(b){return a.rightoffold(b,{threshold:0})},"left-of-screen":function(b){return!a.rightoffold(b,{threshold:0})},"in-viewport":function(b){return a.inviewport(b,{threshold:0})},"above-the-fold":function(b){return!a.belowthefold(b,{threshold:0})},"right-of-fold":function(b){return a.rightoffold(b,{threshold:0})},"left-of-fold":function(b){return!a.rightoffold(b,{threshold:0})}})}(jQuery,window,
document);
jQuery.fn.highlightFade=function(a){var b=a&&a.constructor==String?{start:a}:a||{},c=jQuery.highlightFade.defaults,d=b.interval||c.interval,g=b.attr||c.attr,a={linear:function(a,b,c,d){return parseInt(a+d/c*(b-a))},sinusoidal:function(a,b,c,d){return parseInt(a+Math.sin(90*(d/c)*(Math.PI/180))*(b-a))},exponential:function(a,b,c,d){return parseInt(a+Math.pow(d/c,2)*(b-a))}},f=b.iterator&&b.iterator.constructor==Function?b.iterator:a[b.iterator]||a[c.iterator]||a.linear;c.iterator&&c.iterator.constructor==Function&&
(f=c.iterator);return this.each(function(){this.highlighting||(this.highlighting={});var a=this.highlighting[g]?this.highlighting[g].end:jQuery.highlightFade.getBaseValue(this,g)||[255,255,255],i=jQuery.highlightFade.getRGB(b.start||b.colour||b.color||c.start||[255,255,128]),j=jQuery.speed(b.speed||c.speed),h=b["final"]||this.highlighting[g]&&this.highlighting[g].orig?this.highlighting[g].orig:jQuery.curCSS(this,g);if(b.end||c.end)h=jQuery.highlightFade.asRGBString(a=jQuery.highlightFade.getRGB(b.end||
c.end));"undefined"!=typeof b["final"]&&(h=b["final"]);this.highlighting[g]&&this.highlighting[g].timer&&window.clearInterval(this.highlighting[g].timer);this.highlighting[g]={steps:j.duration/d,interval:d,currentStep:0,start:i,end:a,orig:h,attr:g};jQuery.highlightFade(this,g,b.complete,f)})};
jQuery.highlightFade=function(a,b,c,d){a.highlighting[b].timer=window.setInterval(function(){var g=d(a.highlighting[b].start[0],a.highlighting[b].end[0],a.highlighting[b].steps,a.highlighting[b].currentStep),f=d(a.highlighting[b].start[1],a.highlighting[b].end[1],a.highlighting[b].steps,a.highlighting[b].currentStep),e=d(a.highlighting[b].start[2],a.highlighting[b].end[2],a.highlighting[b].steps,a.highlighting[b].currentStep);jQuery(a).css(b,jQuery.highlightFade.asRGBString([g,f,e]));a.highlighting[b].currentStep++>=
a.highlighting[b].steps&&(jQuery(a).css(b,a.highlighting[b].orig||""),window.clearInterval(a.highlighting[b].timer),a.highlighting[b]=null,c&&c.constructor==Function&&c.call(a))},a.highlighting[b].interval)};jQuery.highlightFade.defaults={start:[255,255,128],interval:50,speed:400,attr:"backgroundColor"};
jQuery.highlightFade.getRGB=function(a,b){var c;return a&&a.constructor==Array&&3==a.length?a:(c=/rgb\(\s*([0-9]{1,3})\s*,\s*([0-9]{1,3})\s*,\s*([0-9]{1,3})\s*\)/.exec(a))?[parseInt(c[1]),parseInt(c[2]),parseInt(c[3])]:(c=/rgb\(\s*([0-9]+(?:\.[0-9]+)?)\%\s*,\s*([0-9]+(?:\.[0-9]+)?)\%\s*,\s*([0-9]+(?:\.[0-9]+)?)\%\s*\)/.exec(a))?[2.55*parseFloat(c[1]),2.55*parseFloat(c[2]),2.55*parseFloat(c[3])]:(c=/#([a-fA-F0-9]{2})([a-fA-F0-9]{2})([a-fA-F0-9]{2})/.exec(a))?[parseInt("0x"+c[1]),parseInt("0x"+c[2]),
parseInt("0x"+c[3])]:(c=/#([a-fA-F0-9])([a-fA-F0-9])([a-fA-F0-9])/.exec(a))?[parseInt("0x"+c[1]+c[1]),parseInt("0x"+c[2]+c[2]),parseInt("0x"+c[3]+c[3])]:jQuery.highlightFade.checkColorName(a)||b||null};jQuery.highlightFade.asRGBString=function(a){return"rgb("+a.join(",")+")"};
jQuery.highlightFade.getBaseValue=function(a,b,c){var d,g,c=c||!1;g=b=b||jQuery.highlightFade.defaults.attr;do{d=jQuery(a).css(g||"backgroundColor");if(""!=d&&"transparent"!=d||"body"==a.tagName.toLowerCase()||!c&&a.highlighting&&a.highlighting[b]&&a.highlighting[b].end)break;g=!1}while(a=a.parentNode);!c&&(a.highlighting&&a.highlighting[b]&&a.highlighting[b].end)&&(d=a.highlighting[b].end);if(void 0==d||""==d||"transparent"==d)d=[255,255,255];return jQuery.highlightFade.getRGB(d)};
jQuery.highlightFade.checkColorName=function(a){if(!a)return null;switch(a.replace(/^\s*|\s*$/g,"").toLowerCase()){case "aqua":return[0,255,255];case "black":return[0,0,0];case "blue":return[0,0,255];case "fuchsia":return[255,0,255];case "gray":return[128,128,128];case "green":return[0,128,0];case "lime":return[0,255,0];case "maroon":return[128,0,0];case "navy":return[0,0,128];case "olive":return[128,128,0];case "purple":return[128,0,128];case "red":return[255,0,0];case "silver":return[192,192,192];
case "teal":return[0,128,128];case "white":return[255,255,255];case "yellow":return[255,255,0]}};
(function(a){function b(d,g){var d=a(d),j=d.clone().empty(),h;d.contents().each(function(){var a=g-j.text().length;0!=a&&(h=3==this.nodeType?c(this,a):b(this,a))&&j.append(h)});return j}function c(b,c){var g=d(b.data);f&&(g=g.replace(/^ /,""));f=!!g.match(/ $/);g=g.slice(0,c);return g=a("<div/>").text(g).html()}function d(a){return a.replace(/\s+/g," ")}function g(b){var c=a(b),d=c.children(":last");if(!d)return b;b=d.css("display");return!b||"inline"==b?c:g(d)}var f=!0;a.fn.truncate=function(e){var i=
a.extend({},a.fn.truncate.defaults,e);a(this).each(function(){if(!(a.trim(d(a(this).text())).length<=i.max_length)){var e=i.max_length-i.more.length-(i.overhead_length||3),h=3==this.nodeType?c(this,e):b(this,e),f=a(this).hide();h.insertAfter(f);g(h).append(i.more_html||' (<a href="#show more content">'+i.more+"</a>)");e=(e=a(f).children(":last"))&&e.is("p")?e:f;e.append(i.less_html||' (<a href="#show less content">'+i.less+"</a>)");h.find("a:last").click(function(){h.hide();f.show();return!1});f.find("a:last").click(function(){h.show();
f.hide();return!1})}})};a.fn.truncate.defaults={max_length:100,more:"\u2026more",less:"less"}})(jQuery);(function(){$(function(){$(".copyright").one("click",".smt-trigger",function(){$(".smt-menu ul").css({bottom:$(".smt-menu").height()})})})})();function MessageBar(a){this.config=a||{};this.slideDownTime=this.config.slideDownTime||500;this.init()}
MessageBar.prototype.init=function(){this.container=$(".global-message-bar-container");this.messageContainer=this.container.find(".message");this.config.messageHTML&&this.messageContainer.html(this.config.messageHTML);this.bindEvents()};
MessageBar.prototype.bindEvents=function(){var a=this;$(this.container).on("click",".close",function(b){b.preventDefault();b.stopPropagation();a.hide()});$(this.container).on("click",function(b){a.config.contentClickCallback&&a.config.contentClickCallback.apply(this,[b,a.config.contentClickCallbackArgs])})};MessageBar.prototype.hide=function(){this.container.slideUp();this.config.hideCallBack&&this.config.hideCallBack.apply(this.container,[this.config.hideCallBackArgs])};
MessageBar.prototype.show=function(){this.container.slideDown(this.slideDownTime);this.config.showCallBack&&this.config.showCallBack.apply(this.container,[this.config.showCallBackArgs])};
!function(a,b){var c,d,g=a.document,f=a.navigator,e=a.setTimeout,i=a.encodeURIComponent,j=a.ActiveXObject,h=a.Error,p=a.Number.parseInt||a.parseInt,w=a.Number.parseFloat||a.parseFloat,m=a.Number.isNaN||a.isNaN,r=a.Math.round,F=a.Date.now,T=a.Object.keys,J=a.Object.defineProperty,v=a.Object.prototype.hasOwnProperty,fa=a.Array.prototype.slice,U,y=function(a){return a};if("function"==typeof a.wrap&&"function"==typeof a.unwrap)try{var z=g.createElement("div"),G=a.unwrap(z);1===z.nodeType&&G&&1===G.nodeType&&
(y=a.unwrap)}catch(Ja){}U=y;var s=function(a){return fa.call(a,0)},t=function(){var a,c,B,d,g,e=s(arguments),i=e[0]||{};a=1;for(c=e.length;c>a;a++)if(null!=(B=e[a]))for(d in B)v.call(B,d)&&(g=B[d],i!==g&&g!==b&&(i[d]=g));return i},H=function(a){var b,c,d;if("object"!=typeof a||null==a)b=a;else if("number"==typeof a.length){b=[];c=0;for(d=a.length;d>c;c++)v.call(a,c)&&(b[c]=H(a[c]))}else for(c in b={},a)v.call(a,c)&&(b[c]=H(a[c]));return b},V=function(a,b){if(a&&1===a.nodeType&&a.ownerDocument&&b&&
(1===b.nodeType&&b.ownerDocument&&b.ownerDocument===a.ownerDocument||9===b.nodeType&&!b.ownerDocument&&b===a.ownerDocument)){do{if(a===b)return!0;a=a.parentNode}while(a)}return!1},y=function(a){var b;return"string"==typeof a&&a&&(a.split("#")[0].split("?"),b=a.slice(0,a.lastIndexOf("/")+1)),b},q={bridge:null,version:"0.0.0",pluginType:"unknown",disabled:null,outdated:null,unavailable:null,deactivated:null,overdue:null,ready:null},C={},u={},P=null,ha={ready:"Flash communication is established",error:{"flash-disabled":"Flash is disabled or not installed",
"flash-outdated":"Flash is too outdated to support ZeroClipboard","flash-unavailable":"Flash is unable to communicate bidirectionally with JavaScript","flash-deactivated":"Flash is too outdated for your browser and/or is configured as click-to-activate","flash-overdue":"Flash communication was established but NOT within the acceptable time limit"}};if(!(z=y(function(){var a,c,B;if(g.currentScript&&(a=g.currentScript.src))return a;if(c=g.getElementsByTagName("script"),1===c.length)return c[0].src||
b;if("readyState"in c[0])for(B=c.length;B--;)if("interactive"===c[B].readyState&&(a=c[B].src))return a;var d;if("loading"===g.readyState&&(a=c[c.length-1].src))d=a;else{var e;try{throw new h;}catch(i){c=i}if(c&&!(e=c.sourceURL))if(!(e=c.fileName)){e=c.stack;var f;e=("string"==typeof e&&e&&(f=e.match(/^(?:|[^:@]*@|.+\)@(?=http[s]?|file)|.+?\s+(?: at |@)(?:[^:\(]+ )*[\(]?)((?:http[s]?|file):\/\/[\/]?.+?\/[^:\)]*?)(?::\d+)(?::\d+)?/),f&&f[1]?d=f[1]:(f=e.match(/\)@((?:http[s]?|file):\/\/[\/]?.+?\/[^:\)]*?)(?::\d+)(?::\d+)?/),
f&&f[1]&&(d=f[1]))),d)}d=(a=e)?a:b}return d}()))){for(var D,W=g.getElementsByTagName("script"),z=W.length;z--;){if(!(G=W[z].src)){D=null;break}if(G=y(G),null==D)D=G;else if(D!==G){D=null;break}}z=D||b||""}var n={swfPath:z+"ZeroClipboard.swf",trustedDomains:a.location.host?[a.location.host]:[],cacheBust:!0,forceEnhancedClipboard:!1,flashLoadTimeout:3E4,autoActivate:!0,bubbleEvents:!0,containerId:"global-zeroclipboard-html-bridge",containerClass:"global-zeroclipboard-container",swfObjectId:"global-zeroclipboard-flash-bridge",
hoverClass:"zeroclipboard-is-hover",activeClass:"zeroclipboard-is-active",forceHandCursor:!1,title:null,zIndex:999999999},ia=function(a){if("object"==typeof a&&null!==a)for(var b in a)if(v.call(a,b))if(/^(?:forceHandCursor|title|zIndex|bubbleEvents)$/.test(b))n[b]=a[b];else if(null==q.bridge){if(("containerId"===b||"swfObjectId"===b)&&!("string"==typeof a[b]&&a[b]&&/^[A-Za-z][A-Za-z0-9_:\-\.]*$/.test(a[b])))throw Error("The specified `"+b+"` value is not valid as an HTML4 Element ID");n[b]=a[b]}if("string"!=
typeof a||!a)return H(n);if(v.call(n,a))return n[a]},ja=function(){for(var a=["userAgent","platform","appName"],b={},c=0,d=a.length;d>c;c++)a[c]in f&&(b[a[c]]=f[a[c]]);var a=["bridge"],c={},g;for(g in q)-1===a.indexOf(g)&&(c[g]=q[g]);return{browser:b,flash:c,zeroclipboard:{version:l.version,config:l.config()}}},ka=function(){return!(!q.disabled&&!q.outdated&&!q.unavailable&&!q.deactivated)},la=function(a,b){var c,d,g,e={};if("string"==typeof a&&a)g=a.toLowerCase().split(/\s+/);else if("object"==typeof a&&
a&&"undefined"==typeof b)for(c in a)v.call(a,c)&&"string"==typeof c&&c&&"function"==typeof a[c]&&l.on(c,a[c]);if(g&&g.length){c=0;for(d=g.length;d>c;c++)a=g[c].replace(/^on/,""),e[a]=!0,C[a]||(C[a]=[]),C[a].push(b);if(e.ready&&q.ready&&l.emit({type:"ready"}),e.error){g=["disabled","outdated","unavailable","deactivated","overdue"];c=0;for(d=g.length;d>c;c++)if(!0===q[g[c]]){l.emit({type:"error",name:"flash-"+g[c]});break}}}return l},ma=function(a,b){var c,d,g,e,f;if(0===arguments.length)e=T(C);else if("string"==
typeof a&&a)e=a.split(/\s+/);else if("object"==typeof a&&a&&"undefined"==typeof b)for(c in a)v.call(a,c)&&"string"==typeof c&&c&&"function"==typeof a[c]&&l.off(c,a[c]);if(e&&e.length){c=0;for(d=e.length;d>c;c++)if(a=e[c].toLowerCase().replace(/^on/,""),f=C[a],f&&f.length)if(b)for(g=f.indexOf(b);-1!==g;)f.splice(g,1),g=f.indexOf(b,g);else f.length=0}return l},na=function(a){return"string"==typeof a&&a?H(C[a])||null:H(C)},oa=function(k){var b,e,f;if(b=k=X(k)){b=k;var i=b.target||c||null,h="swf"===b._source;
delete b._source;var j=["flash-disabled","flash-outdated","flash-unavailable","flash-deactivated","flash-overdue"];switch(b.type){case "error":-1!==j.indexOf(b.name)&&t(q,{disabled:"flash-disabled"===b.name,outdated:"flash-outdated"===b.name,unavailable:"flash-unavailable"===b.name,deactivated:"flash-deactivated"===b.name,overdue:"flash-overdue"===b.name,ready:!1});break;case "ready":var p=!0===q.deactivated;t(q,{disabled:!1,outdated:!1,unavailable:!1,deactivated:!1,overdue:p,ready:!p});break;case "beforecopy":d=
i;break;case "copy":var r,m=b.relatedTarget;!u["text/html"]&&!u["text/plain"]&&m&&(r=m.value||m.outerHTML||m.innerHTML)&&(p=m.value||m.textContent||m.innerText)?(b.clipboardData.clearData(),b.clipboardData.setData("text/plain",p),r!==p&&b.clipboardData.setData("text/html",r)):!u["text/plain"]&&b.target&&(p=b.target.getAttribute("data-clipboard-text"))&&(b.clipboardData.clearData(),b.clipboardData.setData("text/plain",p));break;case "aftercopy":l.clearData();if(i){try{m=g.activeElement}catch(w){m=
null}i!==m&&i.focus&&i.focus()}break;case "_mouseover":l.focus(i);!0===n.bubbleEvents&&h&&(i&&i!==b.relatedTarget&&!V(b.relatedTarget,i)&&E(t({},b,{type:"mouseenter",bubbles:!1,cancelable:!1})),E(t({},b,{type:"mouseover"})));break;case "_mouseout":l.blur();!0===n.bubbleEvents&&h&&(i&&i!==b.relatedTarget&&!V(b.relatedTarget,i)&&E(t({},b,{type:"mouseleave",bubbles:!1,cancelable:!1})),E(t({},b,{type:"mouseout"})));break;case "_mousedown":Y(i,n.activeClass);!0===n.bubbleEvents&&h&&E(t({},b,{type:b.type.slice(1)}));
break;case "_mouseup":K(i,n.activeClass);!0===n.bubbleEvents&&h&&E(t({},b,{type:b.type.slice(1)}));break;case "_click":d=null;!0===n.bubbleEvents&&h&&E(t({},b,{type:b.type.slice(1)}));break;case "_mousemove":!0===n.bubbleEvents&&h&&E(t({},b,{type:b.type.slice(1)}))}b=!/^_(?:click|mouse(?:over|out|down|up|move))$/.test(b.type)}if(b)if("ready"===k.type&&!0===q.overdue)f=l.emit({type:"error",name:"flash-overdue"});else{b=t({},k);if("object"==typeof b&&(b&&b.type)&&(p=Z(b),(r=(C["*"]||[]).concat(C[b.type]||
[]))&&r.length))for(var J,m=0,i=r.length;i>m;m++)h=r[m],j=this,"string"==typeof h&&"function"==typeof a[h]&&(h=a[h]),"object"==typeof h&&h&&"function"==typeof h.handleEvent&&(j=h,h=h.handleEvent),"function"==typeof h&&(J=t({},b),aa(h,j,[J],p));if("copy"===k.type){e={};k={};if("object"==typeof u&&u){for(f in u)if(f&&v.call(u,f)&&"string"==typeof u[f]&&u[f])switch(f.toLowerCase()){case "text/plain":case "text":case "air:text":case "flash:text":e.text=u[f];k.text=f;break;case "text/html":case "html":case "air:html":case "flash:html":e.html=
u[f];k.html=f;break;case "application/rtf":case "text/rtf":case "rtf":case "richtext":case "air:rtf":case "flash:rtf":e.rtf=u[f],k.rtf=f}f={data:e,formatMap:k}}else f=void 0;e=f.data;P=f.formatMap}f=e}else f=void 0;return f},pa=function(){if("boolean"!=typeof q.ready&&(q.ready=!1),!l.isFlashUnusable()&&null===q.bridge){var b=n.flashLoadTimeout;"number"==typeof b&&0<=b&&e(function(){"boolean"!=typeof q.deactivated&&(q.deactivated=!0);!0===q.deactivated&&l.emit({type:"error",name:"flash-deactivated"})},
b);q.overdue=!1;var c,b=q.bridge,d=L(b);if(!b){var b=ba(a.location.host,n),f="never"===b?"none":"all",h,j,p,m,d="",r=[];if(n.trustedDomains&&("string"==typeof n.trustedDomains?m=[n.trustedDomains]:"object"==typeof n.trustedDomains&&"length"in n.trustedDomains&&(m=n.trustedDomains)),m&&m.length){j=0;for(p=m.length;p>j;j++)if(v.call(m,j)&&(m[j]&&"string"==typeof m[j])&&!(h=Q(m[j]),!h)){if("*"===h){r.length=0;r.push(h);break}r.push.apply(r,[h,"//"+h,a.location.protocol+"//"+h])}}h=(r.length&&(d+="trustedOrigins="+
i(r.join(","))),!0===n.forceEnhancedClipboard&&(d+=(d?"&":"")+"forceEnhancedClipboard=true"),"string"==typeof n.swfObjectId&&n.swfObjectId&&(d+=(d?"&":"")+"swfObjectId="+i(n.swfObjectId)),d);m=n.swfPath+(null==n||n&&!0===n.cacheBust?(-1===n.swfPath.indexOf("?")?"?":"&")+"noCache="+F():"");d=g.createElement("div");d=(d.id=n.containerId,d.className=n.containerClass,d.style.position="absolute",d.style.left="0px",d.style.top="-9999px",d.style.width="1px",d.style.height="1px",d.style.zIndex=""+R(n.zIndex),
d);j=g.createElement("div");d.appendChild(j);g.body.appendChild(d);p=g.createElement("div");r="activex"===q.pluginType;p.innerHTML='<object id="'+n.swfObjectId+'" name="'+n.swfObjectId+'" width="100%" height="100%" '+(r?'classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000"':'type="application/x-shockwave-flash" data="'+m+'"')+">"+(r?'<param name="movie" value="'+m+'"/>':"")+'<param name="allowScriptAccess" value="'+b+'"/><param name="allowNetworking" value="'+f+'"/><param name="menu" value="false"/><param name="wmode" value="transparent"/><param name="flashvars" value="'+
h+'"/></object>';b=p.firstChild;U(b).ZeroClipboard=l;d.replaceChild(b,j)}b||(b=g[n.swfObjectId],b&&(c=b.length)&&(b=b[c-1]),!b&&d&&(b=d.firstChild));q.bridge=b||null}},qa=function(){l.clearData();l.blur();l.emit("destroy");var a=q.bridge;if(a){var b=L(a);b&&("activex"===q.pluginType&&"readyState"in a?(a.style.display="none",function ga(){if(4===a.readyState){for(var c in a)"function"==typeof a[c]&&(a[c]=null);a.parentNode&&a.parentNode.removeChild(a);b.parentNode&&b.parentNode.removeChild(b)}else e(ga,
10)}()):(a.parentNode&&a.parentNode.removeChild(a),b.parentNode&&b.parentNode.removeChild(b)));q.ready=null;q.bridge=null;q.deactivated=null}l.off()},ra=function(a,b){var c;if("object"==typeof a&&a&&"undefined"==typeof b)c=a,l.clearData();else{if("string"!=typeof a||!a)return;c={};c[a]=b}for(var d in c)"string"==typeof d&&d&&v.call(c,d)&&"string"==typeof c[d]&&c[d]&&(u[d]=c[d])},sa=function(a){if("undefined"==typeof a){if(u)for(var b in u)v.call(u,b)&&delete u[b];P=null}else"string"==typeof a&&v.call(u,
a)&&delete u[a]},ta=function(a){return"undefined"==typeof a?H(u):"string"==typeof a&&v.call(u,a)?u[a]:void 0},ua=function(b){if(b&&1===b.nodeType){c&&(K(c,n.activeClass),c!==b&&K(c,n.hoverClass));c=b;Y(b,n.hoverClass);var d=b.getAttribute("title")||n.title;if("string"==typeof d&&d){var g=L(q.bridge);g&&g.setAttribute("title",d)}if(!(d=!0===n.forceHandCursor))d=a.getComputedStyle(b,null).getPropertyValue("cursor"),d="pointer"===(d&&"auto"!==d||"A"!==b.nodeName?d:"pointer");!0===q.ready&&(q.bridge&&
"function"==typeof q.bridge.setHandCursor?q.bridge.setHandCursor(d):q.ready=!1);var e;if(c&&(e=L(q.bridge)))b=ca(c),t(e.style,{width:b.width+"px",height:b.height+"px",top:b.top+"px",left:b.left+"px",zIndex:""+R(n.zIndex)})}},va=function(){var a=L(q.bridge);a&&(a.removeAttribute("title"),a.style.left="0px",a.style.top="-9999px",a.style.width="1px",a.style.top="1px");c&&(K(c,n.hoverClass),K(c,n.activeClass),c=null)},wa=function(){return c||null},X=function(k){var e;if("string"==typeof k&&k?(e=k,k={}):
"object"==typeof k&&k&&"string"==typeof k.type&&k.type&&(e=k.type),e){!k.target&&/^(copy|aftercopy|_click)$/.test(e.toLowerCase())&&(k.target=d);t(k,{type:e.toLowerCase(),target:k.target||c||null,relatedTarget:k.relatedTarget||null,currentTarget:q&&q.bridge||null,timeStamp:k.timeStamp||F()||null});e=ha[k.type];"error"===k.type&&k.name&&e&&(e=e[k.name]);e&&(k.message=e);"ready"===k.type&&t(k,{target:null,version:q.version});"error"===k.type&&(/^flash-(disabled|outdated|unavailable|deactivated|overdue)$/.test(k.name)&&
t(k,{target:null,minimumVersion:"11.0.0"}),/^flash-(outdated|unavailable|deactivated|overdue)$/.test(k.name)&&t(k,{version:q.version}));"copy"===k.type&&(k.clipboardData={setData:l.setData,clearData:l.clearData});if("aftercopy"===k.type&&(e=P,!("object"!=typeof k||!k||"object"!=typeof e||!e))){var f={},h;for(h in k)if(v.call(k,h))if("success"!==h&&"data"!==h)f[h]=k[h];else{f[h]={};var i=k[h],j;for(j in i)j&&v.call(i,j)&&v.call(e,j)&&(f[h][e[j]]=i[j])}k=f}k.target&&!k.relatedTarget&&(h=k,j=(j=(j=k.target)&&
j.getAttribute&&j.getAttribute("data-clipboard-target"))?g.getElementById(j):null,h.relatedTarget=j);if(k&&/^_(?:click|mouse(?:over|out|down|up|move))$/.test(k.type)){h=k.target;j="_mouseover"===k.type&&k.relatedTarget?k.relatedTarget:b;e="_mouseout"===k.type&&k.relatedTarget?k.relatedTarget:b;var i=ca(h),f=i.left+("number"==typeof k._stageX?k._stageX:0),i=i.top+("number"==typeof k._stageY?k._stageY:0),p=f-(g.body.scrollLeft+g.documentElement.scrollLeft),m=i-(g.body.scrollTop+g.documentElement.scrollTop),
r=(a.screenLeft||a.screenX||0)+p,n=(a.screenTop||a.screenY||0)+m,J="number"==typeof k.movementX?k.movementX:0,w="number"==typeof k.movementY?k.movementY:0;delete k._stageX;delete k._stageY;t(k,{srcElement:h,fromElement:j,toElement:e,screenX:r,screenY:n,pageX:f,pageY:i,clientX:p,clientY:m,x:p,y:m,movementX:J,movementY:w,offsetX:0,offsetY:0,layerX:0,layerY:0})}return k}},Z=function(a){return!/^(?:(?:before)?copy|destroy)$/.test(a&&"string"==typeof a.type&&a.type||"")},aa=function(a,b,c,d){d?e(function(){a.apply(b,
c)},0):a.apply(b,c)},E=function(b){if(b&&"string"==typeof b.type&&b){var c,d=b.target||null,e=d&&d.ownerDocument||g,b=t({view:e.defaultView||a,canBubble:!0,cancelable:!0,detail:"click"===b.type?1:0,button:"number"==typeof b.which?b.which-1:"number"==typeof b.button?b.button:e.createEvent?0:1},b);d&&e.createEvent&&d.dispatchEvent&&(b=[b.type,b.canBubble,b.cancelable,b.view,b.detail,b.screenX,b.screenY,b.clientX,b.clientY,b.ctrlKey,b.altKey,b.shiftKey,b.metaKey,b.button,b.relatedTarget],c=e.createEvent("MouseEvents"),
c.initMouseEvent&&(c.initMouseEvent.apply(c,b),c._source="js",d.dispatchEvent(c)))}},L=function(a){for(a=a&&a.parentNode;a&&"OBJECT"===a.nodeName&&a.parentNode;)a=a.parentNode;return a||null},Q=function(a){if(null==a||""===a||(a=a.replace(/^\s+|\s+$/g,""),""===a))return null;var b=a.indexOf("//"),a=-1===b?a:a.slice(b+2),c=a.indexOf("/");return a=-1===c?a:-1===b||0===c?null:a.slice(0,c),a&&".swf"===a.slice(-4).toLowerCase()?null:a||null},ba;ba=function(a,b){var c=Q(b.swfPath);null===c&&(c=a);var d=
b.trustedDomains,e,g,f,h=[];if(!("string"==typeof d&&(d=[d]),"object"!=typeof d||!d||"number"!=typeof d.length)){e=0;for(g=d.length;g>e;e++)if(v.call(d,e)&&(f=Q(d[e]))){if("*"===f){h.length=0;h.push("*");break}-1===h.indexOf(f)&&h.push(f)}}d=h.length;if(0<d){if(1===d&&"*"===h[0])return"always";if(-1!==h.indexOf(a))return 1===d&&a===c?"sameDomain":"always"}return"never"};var Y=function(a,b){if(!a||1!==a.nodeType)return a;if(a.classList)return a.classList.contains(b)||a.classList.add(b),a;if(b&&"string"==
typeof b){var c=(b||"").split(/\s+/);if(1===a.nodeType)if(a.className){for(var d=" "+a.className+" ",e=a.className,g=0,f=c.length;f>g;g++)0>d.indexOf(" "+c[g]+" ")&&(e+=" "+c[g]);a.className=e.replace(/^\s+|\s+$/g,"")}else a.className=b}return a},K=function(a,b){if(!a||1!==a.nodeType)return a;if(a.classList)return a.classList.contains(b)&&a.classList.remove(b),a;if("string"==typeof b&&b){var c=b.split(/\s+/);if(1===a.nodeType&&a.className){for(var d=(" "+a.className+" ").replace(/[\n\t]/g," "),e=
0,g=c.length;g>e;e++)d=d.replace(" "+c[e]+" "," ");a.className=d.replace(/^\s+|\s+$/g,"")}}return a},ca=function(b){var c={left:0,top:0,width:0,height:0};if(b.getBoundingClientRect){var d,e,b=b.getBoundingClientRect();if("pageXOffset"in a&&"pageYOffset"in a)d=a.pageXOffset,e=a.pageYOffset;else{var f,h;e=("function"==typeof g.body.getBoundingClientRect&&(d=g.body.getBoundingClientRect(),f=d.right-d.left,h=g.body.offsetWidth,r(100*(f/h))),1);d=r(g.documentElement.scrollLeft/e);e=r(g.documentElement.scrollTop/
e)}f=g.documentElement.clientTop||0;c.left=b.left+d-(g.documentElement.clientLeft||0);c.top=b.top+e-f;c.width="width"in b?b.width:b.right-b.left;c.height="height"in b?b.height:b.bottom-b.top}return c},R=function(a){if(/^(?:auto|inherit)$/.test(a))return a;var b;return"number"!=typeof a||m(a)?"string"==typeof a&&(b=R(p(a,10))):b=a,"number"==typeof b?b:"auto"},N=function(a){a=a.match(/[\d]+/g);return a.length=3,a.join(".")};D=function(a){a&&(I=!0,a.version&&(A=N(a.version)),!A&&a.description&&(A=N(a.description)),
a.filename&&(a=a.filename,da=!!a&&(a=a.toLowerCase())&&(/^(pepflashplayer\.dll|libpepflashplayer\.so|pepperflashplayer\.plugin)$/.test(a)||"chrome.plugin"===a.slice(-13))))};var M,I=!1,da=y=!1,A="";if(f.plugins&&f.plugins.length)j=f.plugins["Shockwave Flash"],D(j),f.plugins["Shockwave Flash 2.0"]&&(I=!0,A="2.0.0.11");else if(f.mimeTypes&&f.mimeTypes.length)j=(j=f.mimeTypes["application/x-shockwave-flash"])&&j.enabledPlugin,D(j);else if("undefined"!=typeof j){y=!0;try{M=new j("ShockwaveFlash.ShockwaveFlash.7"),
I=!0,A=N(M.GetVariable("$version"))}catch(Ka){try{M=new j("ShockwaveFlash.ShockwaveFlash.6"),I=!0,A="6.0.21"}catch(La){try{M=new j("ShockwaveFlash.ShockwaveFlash"),I=!0,A=N(M.GetVariable("$version"))}catch(Ma){y=!1}}}}q.disabled=!0!==I;q.outdated=A&&w(A)<w("11.0.0");q.version=A||"0.0.0";q.pluginType=da?"pepper":y?"activex":I?"netscape":"unknown";var l=function(){return this instanceof l?void("function"==typeof l._createClient&&l._createClient.apply(this,s(arguments))):new l};J(l,"version",{value:"2.1.6",
writable:!1,configurable:!0,enumerable:!0});l.config=function(){return ia.apply(this,s(arguments))};l.state=function(){return ja.apply(this,s(arguments))};l.isFlashUnusable=function(){return ka.apply(this,s(arguments))};l.on=function(){return la.apply(this,s(arguments))};l.off=function(){return ma.apply(this,s(arguments))};l.handlers=function(){return na.apply(this,s(arguments))};l.emit=function(){return oa.apply(this,s(arguments))};l.create=function(){return pa.apply(this,s(arguments))};l.destroy=
function(){return qa.apply(this,s(arguments))};l.setData=function(){return ra.apply(this,s(arguments))};l.clearData=function(){return sa.apply(this,s(arguments))};l.getData=function(){return ta.apply(this,s(arguments))};l.focus=l.activate=function(){return ua.apply(this,s(arguments))};l.blur=l.deactivate=function(){return va.apply(this,s(arguments))};l.activeElement=function(){return wa.apply(this,s(arguments))};var xa=0,x={},ya=0,O={},S={};t(n,{autoActivate:!0});var za=function(a){var b=this;b.id=
""+xa++;x[b.id]={instance:b,elements:[],handlers:{}};a&&b.clip(a);l.on("*",function(a){return b.emit(a)});l.on("destroy",function(){b.destroy()});l.create()},Aa=function(a,b){var c,d,e,g={},f=x[this.id]&&x[this.id].handlers;if("string"==typeof a&&a)e=a.toLowerCase().split(/\s+/);else if("object"==typeof a&&a&&"undefined"==typeof b)for(c in a)v.call(a,c)&&"string"==typeof c&&c&&"function"==typeof a[c]&&this.on(c,a[c]);if(e&&e.length){c=0;for(d=e.length;d>c;c++)a=e[c].replace(/^on/,""),g[a]=!0,f[a]||
(f[a]=[]),f[a].push(b);if(g.ready&&q.ready&&this.emit({type:"ready",client:this}),g.error){e=["disabled","outdated","unavailable","deactivated","overdue"];c=0;for(d=e.length;d>c;c++)if(q[e[c]]){this.emit({type:"error",name:"flash-"+e[c],client:this});break}}}return this},Ba=function(a,b){var c,d,e,g,f,h=x[this.id]&&x[this.id].handlers;if(0===arguments.length)g=T(h);else if("string"==typeof a&&a)g=a.split(/\s+/);else if("object"==typeof a&&a&&"undefined"==typeof b)for(c in a)v.call(a,c)&&"string"==
typeof c&&c&&"function"==typeof a[c]&&this.off(c,a[c]);if(g&&g.length){c=0;for(d=g.length;d>c;c++)if(a=g[c].toLowerCase().replace(/^on/,""),f=h[a],f&&f.length)if(b)for(e=f.indexOf(b);-1!==e;)f.splice(e,1),e=f.indexOf(b,e);else f.length=0}return this},Ca=function(a){var b=x[this.id]&&x[this.id].handlers;return b&&("string"==typeof a&&a?b[a]&&b[a].slice(0):H(b)),null},Da=function(b){var c;var d=b;if(!d||!d.type)c=!1;else if(d.client&&d.client!==this)c=!1;else{var e=x[this.id]&&x[this.id].elements,g=
!!e&&0<e.length;c=!d.target||g&&-1!==e.indexOf(d.target);e=d.relatedTarget&&g&&-1!==e.indexOf(d.relatedTarget);d=d.client&&d.client===this;c=c||e||d?!0:!1}if(c&&("object"==typeof b&&b&&"string"==typeof b.type&&b.type&&(b=t({},b)),b=t({},X(b),{client:this}),"object"==typeof b&&(b&&b.type)&&(c=Z(b),(d=(x[this.id]&&x[this.id].handlers["*"]||[]).concat(x[this.id]&&x[this.id].handlers[b.type]||[]))&&d.length)))for(var f,h,i,e=0,g=d.length;g>e;e++)f=d[e],h=this,"string"==typeof f&&"function"==typeof a[f]&&
(f=a[f]),"object"==typeof f&&f&&"function"==typeof f.handleEvent&&(h=f,f=f.handleEvent),"function"==typeof f&&(i=t({},b),aa(f,h,[i],c));return this},Fa=function(a){for(var a=ea(a),b=0;b<a.length;b++)if(v.call(a,b)&&a[b]&&1===a[b].nodeType){a[b].zcClippingId?-1===O[a[b].zcClippingId].indexOf(this.id)&&O[a[b].zcClippingId].push(this.id):(a[b].zcClippingId="zcClippingId_"+ya++,O[a[b].zcClippingId]=[this.id],!0===n.autoActivate&&Ea(a[b]));var c=x[this.id]&&x[this.id].elements;-1===c.indexOf(a[b])&&c.push(a[b])}return this},
Ga=function(a){var b=x[this.id];if(!b)return this;for(var c,b=b.elements,a="undefined"==typeof a?b.slice(0):ea(a),d=a.length;d--;)if(v.call(a,d)&&a[d]&&1===a[d].nodeType){for(c=0;-1!==(c=b.indexOf(a[d],c));)b.splice(c,1);var e=O[a[d].zcClippingId];if(e){for(c=0;-1!==(c=e.indexOf(this.id,c));)e.splice(c,1);if(0===e.length){if(!0===n.autoActivate&&(c=a[d])&&1===c.nodeType)if(e=S[c.zcClippingId],"object"==typeof e&&e){for(var g=void 0,f=void 0,h=["move","leave","enter","out","over"],i=0,j=h.length;j>
i;i++)g="mouse"+h[i],f=e[g],"function"==typeof f&&c.removeEventListener(g,f,!1);delete S[c.zcClippingId]}delete a[d].zcClippingId}}}return this},Ha=function(){var a=x[this.id];return a&&a.elements?a.elements.slice(0):[]},Ia=function(){this.unclip();this.off();delete x[this.id]},ea=function(a){return"string"==typeof a&&(a=[]),"number"!=typeof a.length?[a]:a},Ea=function(b){if(b&&1===b.nodeType){var c=function(b){(b||(b=a.event))&&("js"!==b._source&&(b.stopImmediatePropagation(),b.preventDefault()),
delete b._source)},d=function(d){(d||(d=a.event))&&(c(d),l.focus(b))};b.addEventListener("mouseover",d,!1);b.addEventListener("mouseout",c,!1);b.addEventListener("mouseenter",c,!1);b.addEventListener("mouseleave",c,!1);b.addEventListener("mousemove",c,!1);S[b.zcClippingId]={mouseover:d,mouseout:c,mouseenter:c,mouseleave:c,mousemove:c}}};l._createClient=function(){za.apply(this,s(arguments))};l.prototype.on=function(){return Aa.apply(this,s(arguments))};l.prototype.off=function(){return Ba.apply(this,
s(arguments))};l.prototype.handlers=function(){return Ca.apply(this,s(arguments))};l.prototype.emit=function(){return Da.apply(this,s(arguments))};l.prototype.clip=function(){return Fa.apply(this,s(arguments))};l.prototype.unclip=function(){return Ga.apply(this,s(arguments))};l.prototype.elements=function(){return Ha.apply(this,s(arguments))};l.prototype.destroy=function(){return Ia.apply(this,s(arguments))};l.prototype.setText=function(a){return l.setData("text/plain",a),this};l.prototype.setHtml=
function(a){return l.setData("text/html",a),this};l.prototype.setRichText=function(a){return l.setData("application/rtf",a),this};l.prototype.setData=function(){return l.setData.apply(this,s(arguments)),this};l.prototype.clearData=function(){return l.clearData.apply(this,s(arguments)),this};l.prototype.getData=function(){return l.getData.apply(this,s(arguments))};"function"==typeof define&&define.amd?define(function(){return l}):"object"==typeof module&&module&&"object"==typeof module.exports&&module.exports?
module.exports=l:a.ZeroClipboard=l}(function(){return this||window}());
(function(){var a={},b=null,c=null,d=document.title,g=null,f=null,e={},i={width:7,height:9,font:"10px arial",colour:"#ffffff",background:"#F03D25",fallback:!0},j,h=navigator.userAgent.toLowerCase();j=function(a){return-1!==h.indexOf(a)};j("chrome");var p=j("chrome")||j("safari"),w=j("safari")&&!j("chrome"),m=j("mozilla")&&!j("chrome")&&!j("safari"),r=function(){f||(f=document.createElement("canvas"),f.width=16,f.height=16);return f},F=function(){if(r().getContext){for(var a=r().toDataURL(),b=document.getElementsByTagName("link"),
c=document.getElementsByTagName("head")[0],d=0,e=b.length;d<e;d++)"icon"===b[d].getAttribute("rel")&&c.removeChild(b[d]);b=document.createElement("link");b.type="image/x-icon";b.rel="icon";b.href=a;document.getElementsByTagName("head")[0].appendChild(b)}};a.setOptions=function(a){e={};for(var b in i)e[b]=a[b]?a[b]:i[b];return this};a.setImage=function(a){b=a;F();return this};a.setBubble=function(a){if(isNaN(a))window.console&&window.console.log("Bubble must be a number");else{var f=a;if(!r().getContext||
w||"force"===e.fallback)e.fallback&&(document.title=0<f?"("+f+") "+d:d);else{var h=r().getContext("2d"),f=f||0;g=new Image;g.crossOrigin="anonymous";g.onload=function(){h.clearRect(0,0,16,16);h.drawImage(g,0,0,g.width,g.height,0,0,16,16);if(0<f){var a=f,b=e.width+6*((a+"").length-1),c=16-b,d=16-e.height;h.font=(p?"bold ":"")+e.font;h.fillStyle=e.background;h.strokeStyle=e.background;h.lineWidth=1;h.fillRect(c,d,b-1,e.height);h.beginPath();h.moveTo(c-0.5,d+1);h.lineTo(c-0.5,15);h.stroke();h.beginPath();
h.moveTo(15.5,d+1);h.lineTo(15.5,15);h.stroke();h.beginPath();h.strokeStyle="rgba(0,0,0,0.3)";h.moveTo(c,16);h.lineTo(15,16);h.stroke();h.fillStyle=e.colour;h.textAlign="right";h.textBaseline="top";h.fillText(a,15,m?7:6)}F()};a=g;if(!c||!b){var i;b:{i=document.getElementsByTagName("link");for(var j=0,y=i.length;j<y;j++)if((i[j].getAttribute("rel")||"").match(/\bicon\b/)){i=i[j];break b}i=!1}c=b=i?i.getAttribute("href"):"/favicon.ico"}a.src=b}return this}};a.reset=function(){a.setImage(c)};a.setOptions(i);
window.Tinycon=a})();function SSComments(a){"undefined"!==typeof a&&this.setup_comments_interaction(a)}
SSComments.prototype.setup_comments_interaction=function(a){var b=$("#notesList"),c=$("#empty-note"),d=a.svComments.find(".j-post-comment-input"),g=b.find("li").hide(),f=g[0];a.notes={onload:function(a){g.hide();(f=g[a-1])?(c.hide(),f=$(f).show()):c.show()}};var e=a.svComments.find(".j-more-comments");$.extend(a.comments,{slide_number:1,onload:function(b){a.comments.slide_number=b},get_secret_key:function(){return/\/secret\//.test(window.location.href)?window.location.href.match(/\/secret\/(.*)/)[1]:
""},reply_to_comment:function(a){var a=$("#"+a).find(".j-username").html(),b=d.closest(".j-comment-post").offset().top-$("#main-nav").height();$.scrollTo(b,500);d.focus().val("@"+a+" ")},sanitize_action_links:function(){$("#commentsList").find(".j-action-delete, .j-action-block, .j-action-spam").remove()},save_comments:function(){var a=d.val();0<a.length?window.cookie("comments",a,{path:window.location.pathname}):window.cookie("comments",null,{path:window.location.pathname})},delete_saved_comments:function(){null!==
window.cookie("comments")&&window.cookie("comments",null,{path:window.location.pathname})},decorate_comment_user:function(a,b){$(".j-author-photo img",a).each(function(a,c){c.src=b.photo_url;c.alt=b.login});$(".j-author-photo .j-username",a).each(function(a,c){c.href="/"+b.login;c.title=b.login});$(".j-author-photo",a).each(function(a,c){c.href="/"+b.login;c.title=b.user_description});$(".j-author-photo .j-username",a).text(b.name||b.login)},per_page:5,current_page:1,currently_shown:null,setup_scrolling_on_reply:function(){a.svComments.on("click",
".j-reply",function(b){b.preventDefault();a.comments.reply_to_comment($(this).closest("li.comment").attr("id"),a.svCommentsForm)})},show_page:function(b,c,d){var c=c||this.per_page,d=d||$(".comment",a.svComments).length,g=d/c,f=(b-1)*c;f>d-1&&(f=d-1);c=f+c;c>d-1&&(c=d);this.currently_shown=$(".comment",a.svCommentsul).slice(f,c).show();this.current_page=b;1<g?e.show():e.hide();this.current_page>=g&&e.closest(".more-container").hide();$(".commentWrapper li").hover(function(){$(".commentMeta",this).children(".j-comment-actions").removeClass("hide")},
function(){$(".commentMeta",this).children(".j-comment-actions").addClass("hide")});a.comments.setup_scrolling_on_reply();$(".thumbnailGrid").trigger("adjustHeight")}});$(".alertMessage a").click(function(a){a.preventDefault()});$("#login-provider-slideshare").bind("click",a.comments.save_comments);e.click(function(b){b.preventDefault();a.comments.ajaxurl&&a.comments.total_count>a.comments.per_page?($(a.loading_html).appendTo(e.parent()),e.hide(),b=a.comments.get_secret_key(),$.getJSON(a.comments.ajaxurl,
{key:b},function(b){$.each(b,function(b,c){if(b>=a.comments.per_page){var d=$("#commentsTemplate").clone().hide();d.attr("itemprop",c.user_schema_type);""===c.user_occupation?d.children().remove(".j-commenter-role"):$(".j-commenter-role",d).text(", "+c.user_occupation);""===c.user_organization?d.children().remove(".j-commenter-org"):$(".j-commenter-org",d).text(" at "+c.user_organization);a.comments.decorate_comment_user(d,c);$(".commentMeta .commentTimestamp",d).text(c.created_at+" ago");$(".commentText",
d).html(c.body);d[0].id="comment-"+c.comment_id;$(d[0]).find("#confirmDialog").attr("id","confirmDialog-"+c.comment_id);d.addClass("author-"+c.user_id).addClass("comment");d.appendTo(a.svCommentsul)}});a.comments.sanitize_action_links();a.setup_owner_interaction&&a.setup_owner_interaction();$(".j-loading",e.parent()).remove();a.comments.show_page(a.comments.current_page+1)})):a.comments.show_page(a.comments.current_page+1);a.comments.ajaxurl=null});a.svCommentsForm.jssubmit(function(b){a.comments.delete_saved_comments();
a.comments.post_comment(b.target);$(".comment .action-spam").first().hide();$(".comment .action-block").first().hide()});a.comments.show_page(a.comments.current_page,a.comments.per_page,a.comments.total_count);a.svComments.show();a.svCommentsForm.show();-1<$.inArray(getUrlVar("utm_source"),["commentback"])&&$.scrollTo(a.svCommentsForm,{offset:-90});$(".tabs li a",a.svComments).showhide(".svComments .comments-tab, .svComments .notes-tab");loadDataForSlide(slideshare_object.startSlide)};
window.loadDataForSlide=function(a){slideshare_object.topRightAd&&slideshare_object.topRightAd.trigger("refreshAd");if(1==a&&$(".h-player-banner").is(":hidden")){$(".h-player-banner").slideDown("fast");var b;"presentation"==slideshare_object.slideshow.type&&(b="preso");"document"==slideshare_object.slideshow.type&&(b="doc");window._gaq.push(["_trackEvent","bigfoot_slideview",b+"-adshow"])}slideshare_object.comments.onload?(slideshare_object.comments.onload(a),slideshare_object.notes.onload(a)):setTimeout(function(){loadDataForSlide(a)},
100)};
slideshare_object.setup_lazyload=function(){var a=slideshare_object.userimage_placeholder;$([{selector:".commentsWrapper li img",options:{effect:"fadeIn",placeholder:a}},{selector:".favWrapper li .favoriter img",options:{effect:"fadeIn",placeholder:a}},{selector:".downloadWrapper li .downloader img",options:{effect:"fadeIn",placeholder:a}},{selector:".j-related-item img.j-thumbnail",options:{effect:"fadeIn",placeholder:slideshare_object.slideshow_placeholder}},{selector:".j-mobile-ad",options:{}}]).each(function(a,c){$(c.selector).lazyload(c.options)})};
window.pageTracker={_trackPageview:function(){log("_trackPageview",arguments);return!0},_trackEvent:function(){log("_trackEvent",arguments);return!0},_setVar:function(){log("_setVar",arguments);return!0}};window.log=slideshare_object.dev&&window.console?function(){console.log.apply(console,arguments)}:function(){};String.prototype.supplant=function(a){return this.replace(/\{([^{}]*)\}/g,function(b,c){var d=a[c];return"string"===typeof d||"number"===typeof d?d:b})};
(function(a){a.fn.extend({jsclick:function(a){var c=this,d=function(d){a.apply(c,arguments);d.preventDefault();d.stopPropagation()};this.click(d);return d},jschange:function(a){var c=this,d=function(d){a.apply(c,arguments);d.preventDefault();d.stopPropagation()};this.change(d);return d},jssubmit:function(a){var c=this,d=function(d){a.apply(c,arguments);d.preventDefault();d.stopPropagation()};this.submit(d);return d},add_undo:function(a,c){slideshare_object.ajax_undo&&slideshare_object.ajax_undo.push([a,
c,this])},showhide:function(b,c){this.jsclick(function(){a(b,c).toggle();slideshare_object.align_lostchildren&&slideshare_object.align_lostchildren()});return this}})})(jQuery);
slideshare_object.ready=function(){function a(a){var b=$(".assets"),c=b.offset().top+b.height(),b=a.offset().top;a.height();var d=$(".j-related-item").height()||116,d=".j-related-item:nth-child(n+"+Math.ceil((c-b)/d)+")",f=c;$(d).each(function(){var a=$(this).offset().top;if(a>c)return f=a-1,!1});a.height(f-b)}slideshare_object.timer.ready=(new Date).getTime();slideshare_object.ajax_undo=[];slideshare_object.add_undo=function(a,b){slideshare_object.ajax_undo.push([a,b])};$(document).ajaxError(function(a,
b,c,d){log("ajaxError",a,b,c,c.url,d);var f=slideshare_object.ajax_undo.shift();f&&f[2]&&f[2].trigger("ajaxFail",arguments);if(f)f[1](a,b,c,d)});$(document).ajaxSuccess(function(a,b,c){var d=slideshare_object.ajax_undo.shift();d&&d[2]&&d[2].trigger("ajaxOkay",arguments)});slideshare_object.sessid=encodeURIComponent((document.cookie.match(/_cookie_id=([^;]*)/)||[])[1]);slideshare_object.add_deferred=function(a){slideshare_object.deferred||(slideshare_object.deferred={list:[],timeout:null,next_action:function(){log("Wakie wakie!");
var a=slideshare_object.deferred.list.shift();a&&a();slideshare_object.deferred.list[0]&&(slideshare_object.deferred.timeout&&clearTimeout(slideshare_object.deferred.timeout),slideshare_object.deferred.timeout=setTimeout(slideshare_object.deferred.next_action,100))}});slideshare_object.deferred.timeout&&clearTimeout(slideshare_object.deferred.timeout);slideshare_object.deferred.list.push(a);slideshare_object.deferred.timeout=setTimeout(slideshare_object.deferred.next_action,200)};slideshare_object.lead&&
slideshare_object.lead.form_url&&$(".noAdForLead").remove();slideshare_object.slideshowCategories=$("#slideshow-categories");slideshare_object.suonly=$("ul.superuser-only");slideshare_object.svComments=jQuery(".commentsNotes");slideshare_object.svCommentsul=jQuery("#commentsList");slideshare_object.svCommentsForm=$("form.j-comment-post");slideshare_object.svTools=$(".j-tools");slideshare_object.svEmbed=$(".details .embed");slideshare_object.loading_html='<span class="j-loading">Loading <img alt="Loading&hellip;" src="//public.slidesharecdn.com/images/indicator.gif" height="5" width="21" style="margin:0;float:none;vertical-align:middle" /></span>';
var b;b=".slideshow-communities";$(b+".h-not-truncated")[0]&&$(b+" a.ilink").showhide(b);$(".h-toggle-description").click(function(){"more"==$(this).html()?$(this).html("less"):$(this).html("more");$(".description.h-not-truncated").slideToggle("fast");return!1});var c=[];$(document).ready(function(){var a={};$(".j-share-item").on("click",function(){var b=$(this).data("network"),c=slideshare_object.slideshow.social_urls[b],d=$(this).find(".j-share-count"),f=parseInt(d.html(),10);window.open(c,"shareDialog",
"width=626,height=436");_gaq.push(["_trackEvent","bigfoot_slideview",$(this).data("ga-action")]);void 0===a[b]&&d.html(f+1);a[b]=1});var b=[];$(".j-related-impression").each(function(){b.push({slideshow_id:$(this).data("ssid"),score:$(this).data("score")})});var d=(new Date).getTime(),f=slideshare_object.presentationId+"_"+d,g={module_id:"sv_right",user_id:slideshare_object.user.id,source:slideshare_object.presentationId,recommendations:b,algorithmId:$($(".j-related-impression")[0]).data("algo-id")},
w={recommendation_id:f};void 0!==getUrlVar("related")?g.trackingCode="related":void 0!==getUrlVar("next_slideshow")&&(g.trackingCode="next_slideshow");slideshare_object.push_event_instantly("recommendation_impression",w,g);"37231979"==slideshare_object.presentationId&&(_gaq.push(["_trackEvent","bigfoot_slideview","37231979_recommendation_impression"]),slideshare_object.push_event_instantly("37231979_recommendation_impression",w,g));"37231966"==slideshare_object.presentationId&&(_gaq.push(["_trackEvent",
"bigfoot_slideview","37231966_recommendation_impression"]),slideshare_object.push_event_instantly("37231966_recommendation_impression",w,g));$(player)&&(slideshare_object.track_time.push({slideId:1,time:d}),$(player).bind("slidechanged",function(){d=(new Date).getTime();slideshare_object.track_time.push({slideId:player.controller.currentPosition,time:d});0<player.controller.currentPosition&&3>player.controller.currentPosition&&(g={user_id:slideshare_object.user.id,source:slideshare_object.presentationId,
total_slides:player.controller.slideCount,current_slide:player.controller.currentPosition},slideshare_object.push_event_instantly("slide_level_viewstats",w,g))}),window.onbeforeunload=function(){d=(new Date).getTime();slideshare_object.track_time.push({slideId:player.controller.currentPosition,time:d});g={user_id:slideshare_object.user.id,source:slideshare_object.presentationId,total_slides:player.controller.slideCount,time_spent:slideshare_object.track_time};void 0!==getUrlVar("related")?g.trackingCode=
"related":void 0!==getUrlVar("next_slideshow")&&(g.trackingCode="next_slideshow");slideshare_object.push_events("slideshow_viewstats",w,g)});$(".j-action-categorize").on("click",function(){$(".j-overlay-categorize").toggle();$(window).scrollTop(0)});$(".j-action-sucategorize-submit").click(function(a){a.preventDefault();$(".j-progress").show();a=$("#featured_value option:selected").val();$.post(slideshare_object.su.post_homepage_url,{featured_value:a});var b=$("#slideshow_type").get(0),a="/slideshow/update_editor_details/"+
slideshare_object.presentationId,c=$("#categorize-form").serialize();$.post(a,c,function(){$(".j-progress").hide();$(".j-overlay-categorize").hide();b&&!0===b.checked&&window.location.reload()},"json")});$(".action-sucategorize-cancel").click(function(){$(".j-progress").hide();$(".j-overlay-categorize").hide()});$("#new_title").keyup(function(){$(".new_title_length").text($("#new_title").val().length+" chars")});$(".j-menu-loading").hide();f=c.pop();$(f).click();"haikudeck"===document.referrer.split("/").pop()&&
(new MessageBar).show();$(".j-haikudeck-create").bind("click",function(){window._gaq.push(["_trackEvent","create_cta","click","slideview_side_arrow"])});$('a[href="/login"]').filter(":not(.void_redirect_link)").attr("href","/login?from_source="+encodeURIComponent(window.location.pathname));$(".headerSearch input.text").focus(function(){"Search"==$(this).val()&&$(this).val("")});$(".headerSearch input.text").blur(function(){$(this).val($.trim($(this).val()));""===$(this).val()&&$(this).val("Search")});
$(".headerSearch").submit(function(a){var b=$(this).find("input.text");b.val($.trim(b.val()));if("Search"==b.val()||""===b.val())a.preventDefault(),b.focus()});$(".j-related-impression").bind("click",function(a){a.preventDefault();var b=(new Date).getTime(),a=$(this).data("ssrank"),b=slideshare_object.presentationId+"_"+b+"_"+a,a={moduleId:"right_sidebar_solr",source:slideshare_object.presentationId,target:$(this).data("ssid"),position:a,action:"CLICK",algorithmId:$(this).data("algo-id")};slideshare_object.push_events("recommendation_action",
{recommendationId:b},a);related_position=0;$.slideshareEventManager&&($.slideshareEventManager.controller&&$.slideshareEventManager.controller.config)&&(related_position=$.slideshareEventManager.controller.config.related_position);related_position++;a="";a=$(this);a=a.data("href")?a.data("href"):a.attr("href");window.location.href=a+"?related="+related_position});$(".j-related-impression").mousedown(function(a){var b=$(this);if(2===a.button&&!b.data("href")){var a=(new Date).getTime(),c=b.data("ssrank"),
d={recommendationId:slideshare_object.presentationId+"_"+a+"_"+c},c={moduleId:"right_sidebar_solr",source:slideshare_object.presentationId,target:b.data("ssid"),position:c,action:"CLICK",algorithmId:b.data("algo-id"),click_type:"right click"},d=JSON.stringify({name:"recommendation_action",time:a,data:c,entity:d}),a=b.attr("href"),d="/trackdata?link="+a+"&meta="+d;b.attr("data-href",a);b.attr("href",d);return!1}return!0});$("a.j-view_more").click(function(){$(this).prev().addClass("transcript-content-top-full-height");
$(this).next().removeClass("hide");$(this).addClass("hide");$(".viralShare").css("top",$(".slideviewActions").offset().top-16+"px")});$("a.j-view_less").click(function(){$first_li=$($(this).siblings("ol").children()[0]);$first_li.attr("id","transcripts_ol");$(this).addClass("hide");$(this).prev().removeClass("hide");$(this).prev().prev().removeClass("transcript-content-top-full-height");$(".viralShare").css("top",$(".slideviewActions").offset().top-16+"px")});f=getUrlVar("fb_source");if(getUrlVar("code")||
f)f?slideshare_object.ga("fb_opengraph","slideview_visit",f):slideshare_object.ga("fb_opengraph","slideview_visit","no_fb_source");slideshare_object.processAdQueue&&slideshare_object.processAdQueue();slideshare_object.topRightAd=$(".j-top-right-div iframe");slideshare_object.topRightAd.length&&slideshare_object.topRightAd.bind("refreshAd",function(){var a=0,b=0,c=slideshare_object.topRightAd.attr("src"),c=c.replace(escape("adsense=t;"),"");return function(){a+=1;if(5===a){a=0;b++;var d=slideshare_object.topRightAd,
e=c+escape(";refreshcount="+b),f=d.clone(!0);d.replaceWith(f);f.attr("src",e);slideshare_object.topRightAd=f}}}());var m=window.setInterval(function(){var a,b,c,d;b=$(".transcriptAd iframe");if(!b.length)return function(){window.clearInterval(m)};c=$(window);d=c.height();a=$(".footer-leaderboard-ad").offset().top;return function(){c.scrollTop()+d>=a&&(slideshare_object.loadDelayedLIAd(b,$(".transcriptAd a.j-cta_remove_ad_fancy")),window.clearInterval(m))}}(),500);slideshare_object.action_from_email_check()});
slideshare_object.timer.end=(new Date).getTime();slideshare_object.dev&&window.console&&console.log("ready:",slideshare_object.timer.ready-slideshare_object.timer.start,"total:",slideshare_object.timer.end-slideshare_object.timer.start);b=$("#relatedList");var d=$("#moreList"),g=null;b.length?g=b:d.length&&(g=d);g&&a(g);var f=$(".thumbnailGrid").size();$(".thumbnailGrid").bind("adjustHeight",function(){$(this).hasClass("activeContent")?a($(this)):1==f&&a($(this))})};slideshare_object.timer={start:(new Date).getTime()};
slideshare_object.remove_if_blank=function(a){window.jQuery&&1>jQuery(a+" > *:not(script)").length&&jQuery(a).remove()};
window.cookie=function(a,b,c){if("undefined"!=typeof b){c=c||{};null===b&&(b="",c.expires=-1);var d="";if(c.expires&&("number"==typeof c.expires||c.expires.toUTCString))"number"==typeof c.expires?(d=new Date,d.setTime(d.getTime()+864E5*c.expires)):d=c.expires,d="; expires="+d.toUTCString();var g=c.path?"; path="+c.path:"",f=c.domain?"; domain="+c.domain:"",c=c.secure?"; secure":"";document.cookie=[a,"=",encodeURIComponent(b),d,g,f,c].join("")}else{b=null;if(document.cookie&&""!==document.cookie){c=
document.cookie.split(";");for(d=0;d<c.length;d++)if(g=jQuery.trim(c[d]),g.substring(0,a.length+1)==a+"="){b=decodeURIComponent(g.substring(a.length+1));break}}return b}};$.getScript=function(a,b,c){$.ajax({type:"GET",url:a,success:b,dataType:"script",cache:c})};setTimeout(function(){$(".thumbnailGrid").trigger("adjustHeight")},1E3);
slideshare_object.setup_activitylist_interaction=function(){function a(a,c,d){$(a.meta,c).html(d.summary);a.tag&&$(a.tag,c).html(d.tags);$(a.role,c).text(null===d.user_occupation?"":d.user_occupation);$(a.org,c).text(d.user_organization);$(a.user_link,c).each(function(c,f){f.href="/"+d.login;f.title=d.user_description;$("img",f).each(function(a,b){b.src=d.photo;b.alt=d.login});$(a.username,f).text(d.user_name)});c[0].className=d.css_class}$.each({favs:{container:"#favsList",action_more:".j-more-favs",
meta:slideshare_object.activities.favorites,fill_template:function(b,c){a({meta:".favoriteMeta",tags:".j-tags",role:".j-favoriter-role",org:".j-favoriter-org",user_link:".favoriter",username:".j-username"},b,c)}},downloads:{container:".j-downloads-list",action_more:".j-more-downloads",meta:slideshare_object.activities.downloads,fill_template:function(b,c){a({meta:".downloadMeta",role:".j-downloader-role",org:".j-downloader-org",user_link:".downloader",username:".j-username"},b,c)}}},function(a,c){var d=
$(c.container),g=null;$("li:first",d).each(function(a,b){g=b.cloneNode(!0)});if(c.meta&&g&&c.meta.count<c.meta.total){var f=$(c.action_more);"favs"==a&&f.show();f.jsclick(function(){var a=f.html();f.html(slideshare_object.loading_html);var b=$("li",d).length;$.getJSON(c.meta.url+"?offset="+b,function(b){var h=document.createDocumentFragment();$.each(b,function(a,b){var d=$(g.cloneNode(!0));c.fill_template(d,b);h.appendChild(d[0])});d.append(h);$("li",d).length<c.meta.total?f.html(a):f.remove();$(".thumbnailGrid").trigger("adjustHeight")})})}})};
slideshare_object.download_interaction=function(){this.downloadAction=slideshare_object.svTools.find(".j-download");if(!slideshare_object.lead||!slideshare_object.lead.for_download)if(slideshare_object.user.loggedin)this._init();else if(this._init_loggedout(),window.location.href.match(/redirected_from=save_on_embed/)){var a=this;login_modal_elem=document.getElementById("login_modal");if(null!==login_modal_elem)initiate_login_modal(a.downloadAction.data("href"),a.downloadAction.data("target"));else $(document).on("modalSignupLoaded",
function(){initiate_login_modal(a.downloadAction.data("href"),a.downloadAction.data("target"))})}};slideshare_object.download_interaction.prototype._init_loggedout=function(){this.downloadAction.click(function(){$(".player").hasClass("fullscreen")&&$.slideshareEventManager&&$.slideshareEventManager.trigger("leavefullscreen")})};
slideshare_object.download_interaction.prototype._init=function(){var a=this;slideshare_object.downloads&&slideshare_object.downloads.allow&&$(".j-action-no-download",slideshare_object.svTools).hide();slideshare_object.unverified_user?$(".j-action-download, .j-download",slideshare_object.svTools).unbind("click").click(function(b){b.preventDefault();a.show();$(this).hasClass("current")&&$.get(document.location.pathname+"/download",{from:"slideview.download"},function(a){a.success&&window._gaq.push(["_trackEvent",
"bigfoot_slideview","download>unverified"])},"json")}):$(".j-action-download, .j-download",slideshare_object.svTools).click(function(){window.location.origin||(window.location.origin=window.location.protocol+"//"+window.location.hostname+(window.location.port?":"+window.location.port:""));var a=window.location.origin+this.downloadAction.data("href");window.location.href=a});$(".j-action-unverified-download .cancel").click(function(a){a.preventDefault();a.stopPropagation();$(".j-action-unverified-download").hide();
$(".j-action-download",slideshare_object.svTools).toggleClass("current")})};slideshare_object.download_interaction.prototype.show=function(){this.visible=!0;slideviewInteraction.hideAll();$(".j-action-download").addClass("current");$(".j-action-unverified-download").toggle()};slideshare_object.download_interaction.prototype.hide=function(){this.visible=!1;$(".j-action-download").removeClass("current");$(".j-action-unverified-download").hide()};
function SSContactsFollow(a){"undefined"!==typeof a&&this.setup_slideview_contacts_interaction(a)}SSContactsFollow.prototype.add_contact=function(a,b,c){$.ajax({url:"/contact/create",type:"POST",dataType:"json",data:{contactee:a},success:function(a){a.suspended?window.location.replace("/login"):a.follow_limit_reached?window.location.reload():(""!==a.contactee_fb_id&&slideshare_object.post_activity_to_facebook({name:"follow",facebook_user_id:a.contactee_fb_id},function(){}),b(a))},error:c})};
SSContactsFollow.prototype.delete_contact=function(a,b,c){$.ajax({url:"/contact/delete",type:"POST",dataType:"json",data:{contactee:a},success:function(a){a.success?b(a):c(a)},error:function(a){c(a)}})};
SSContactsFollow.prototype.setup_slideview_contacts_interaction=function(a){var b=!1,c=this;if(a.user.loggedin)$(".j-follow").on("click",function(a){a.preventDefault();var g=$(this);g.find("button:visible");var a=g.data("contactee-id"),f=g.hasClass("following")?"unfollow":"follow";if(!b){g.addClass("loading");b=!0;var e="authorthumbnail>"+f;window._gaq.push(["_trackEvent","bigfoot_slideview",e]);var i=function(a){g.removeClass("loading");a.success?(g.toggleClass("following"),window._gaq.push(["_trackEvent",
"bigfoot_slideview",e+"_failed"]),b=!1):j()},j=function(){g.removeClass("loading");window._gaq.push(["_trackEvent","bigfoot_slideview",e+"_failed"]);b=!1};"follow"===f?c.add_contact(a,i,j):"unfollow"===f&&c.delete_contact(a,i,j)}});else $(".j-follow").on("click",function(){var b={event:"follow",data:{contactee:$(this).data("contactee-id")}};a.addAfterLoginEvent(b)})};
slideshare_object.setup_flagging_interaction=function(){var a=$(".flag-inappropriate form");slideshare_object.flagging=slideshare_object.flagging||{};slideshare_object.flagging={flagged_value:slideshare_object.flagging.flagged_value,update_url:slideshare_object.flagging.update_url,set_as_flagged:function(b){"0"==b?($(".flag-inappropriate .action-flag .flagged").hide(),$(".flag-inappropriate .action-flag .flag").show()):($(".flag-inappropriate .action-flag .flagged").show(),$(".flag-inappropriate .action-flag .flag").hide());
$("select",a).val(b)},post_update:function(){var b=$("select",a).val();slideshare_object.flagging.set_as_flagged(b);$(".flag-inappropriate .action-flag,.flag-inappropriate form").toggle();$.post(slideshare_object.flagging.update_url,{ia_value:b,slideshow_id:slideshare_object.presentationId,source:"slideviewer"},function(a){log(a)})}};slideshare_object.user.loggedin&&($(".flag-inappropriate .action-flag, .flag-inappropriate .action-cancel").click(function(a){a.preventDefault();$(".flag-inappropriate .action-flag, .flag-inappropriate form").toggle("fast")}),
$(".flag-inappropriate .action-submit").jsclick(slideshare_object.flagging.post_update));slideshare_object.flagging.set_as_flagged(slideshare_object.flagging.flagged_value?slideshare_object.flagging.flagged_value:0)};
slideshare_object.embed_interaction=function(a){a=a||{};this.embed_sizes=a.embed_sizes;this.embed_code=a.embed_code;this.wp_code=a.wp_code;this.iframe_code=a.iframe_code;this.iframe_url=a.iframe_url;this.allow_embeds=a.allow_embeds;this.slideshow_type=a.slideshow_type;this.embedHeading="Copy and paste this code into your blog or website";this.wpHeading="Embed code for Wordpress.org blogs";this.zeroclipboardUrl=a.zeroclipboard_url;this._bindEvents();this._isLoaded=!1};
slideshare_object.embed_interaction.prototype._init=function(){$("#h-top-embeds .action-moreembeds, #h-all-embeds .action-lessembeds").showhide("#h-all-embeds,#h-top-embeds");5<slideshare_object.embeds_count?($("#h-top-embeds").show(),$("#h-all-embeds").hide(),$("#h-all-embeds ul").addClass("embedsListExpanded")):($("#h-top-embeds, #h-all-embeds .action-lessembeds").remove(),$("#h-all-embeds").show());if(!this.allow_embeds)return!1;this.iframeIntervalId=this.embedIntervalId=null;this._initCopiers();
this._initCustomization();return!0};
slideshare_object.embed_interaction.prototype._initCopiers=function(){ZeroClipboard.config({swfPath:this.zeroclipboardUrl});this.wp_clipboard=new ZeroClipboard($("#j-wp-copier"));this.iframe_clipboard=new ZeroClipboard($("#j-iframe-copier"));this._initCopier(this.wp_clipboard,{msgBlock:$("#j-wp-msg"),contentBlock:$("#embedCodeWP"),gaLabel:"wp"});this._initCopier(this.iframe_clipboard,{msgBlock:$("#embed-iframe").siblings("span.success"),intervalVar:"iframeIntervalId",contentBlock:$("#embed-iframe"),
gaLabel:"embed"})};slideshare_object.embed_interaction.prototype._initCopier=function(a,b){a.msgBlock=b.msgBlock;a.intervalVar=b.intervalVar;a.contentBlock=b.contentBlock;a.on("ready",function(){a.on("aftercopy",function(){var c=null,d=a.msgBlock;d.text("Copied").fadeIn("slow");c=setTimeout(function(){d.fadeOut("slow")},3E3);a.intervalVar&&(clearTimeout(this[a.intervalVar]),this[a.intervalVar]=c);a.contentBlock.select();window._gaq.push(["_trackEvent","bigfoot_slideview","embedclick",b.gaLabel])})})};
slideshare_object.embed_interaction.prototype._notifyUpdated=function(a){a.contentBlock.highlightFade();a.msgBlock.text("Updated").fadeIn("slow");clearTimeout(this[a.intervalVar]);this[a.intervalVar]=setTimeout(function(){a.msgBlock.fadeOut("slow")},3E3);a.setText(a.contentBlock.val())};
slideshare_object.embed_interaction.prototype._initCustomization=function(){"infographic"==slideshare_object.slideshow.type&&this.changeEmbedSizeAspectRatio();var a=this.embed_sizes,b=$(".j-embed-preset-template:first").removeClass("j-embed-preset-template").remove(),c=$(".j-embed-size"),d=[];$.each(a.presets,function(a){d.push(a)});var d=d.sort(),g=this;$.each(d,function(d,e){var i=b.clone(),j=a.presets[e];j.size.paddedWidth=j.size.width+2;j.size.paddedHeight=j.size.height+1;var h=j.size.paddedWidth+
2,p=j.size.paddedHeight+1;i.find(".j-embed-desc").text(h+" x "+p);i.find(".j-embed-display").width(j.displaySize.width).height(j.displaySize.height);i.attr("id","j_embed_size_"+e);i.bind("click",function(a){a.preventDefault();$(this).parent().find("a span.j-embed-display").removeClass("selected");$(this).find("span.j-embed-display").addClass("selected");g.refreshEmbedCode(!0)});c.append(i);i.show()});$("#j_embed_size_"+a.config.defaultPreset).find("span.j-embed-display").addClass("selected");"video"!=
this.slideshow_type?($("#embed-customize-slidenumber").val(1),$("#embed-customize-withrel, #embed-customize-slidenumber").bind("change",function(){g.refreshEmbedCode(!0)})):$("#embed-customize-withrel, #embed-customize-slidenumber").hide().closest("label").hide()};
slideshare_object.embed_interaction.prototype._bindEvents=function(){$=jQuery;var a=this;$(".action-wpshare").bind("click",function(b){b.preventDefault();b=$("li.expandedOverlay.embedPanel").is(":visible");a.modeToggle("embed");b||(_gaq.push(["_trackEvent","bigfoot_slideview","viralShareWordPressclick"]),$(".customizeEmbed").is(":visible")||$("button.customizeLink").trigger("click"));$("label.j-embed-main-heading").text("Copy and paste this code into your Wordpress blog");return!1});$(".j-action-embed",
slideshare_object.svTools).unbind("click").bind("click",function(){a.modeToggle("embed");$("label.j-embed-main-heading").text("Copy and paste this code into your blog or website")});$(".action-embed-code").on("click",".cancel",function(b){b.preventDefault();a.hide()});$(".action-embed-code").on("click",".h-action-customize",function(b){b.preventDefault();a.toggleCustomize()});$(".action-embed-code").on("click","input[type='text']",function(){this.select()});slideshare_object.svTools.on("click",".j-embed",
function(){slideviewInteraction.hideAll("msharing");$.slideshareEventManager&&($.slideshareEventManager.trigger("playershare","toolbar_"),$("#share-embed-link").focus())});$(".player").on("click",".j-share-embed-link",function(){window._gaq.push(["_trackEvent","bigfoot_slideview","embedclick","embed"])})};
slideshare_object.embed_interaction.prototype.show=function(){var a=this;slideviewInteraction.hideAll("embed");this.visible=!0;$(".j-action-embed").addClass("current");$(".action-embed-code",slideshare_object.svTools).show();this._isLoaded||$.getJSON("/~/slideshow/embed_panel/"+slideshare_object.presentationId).success(function(b){$(".action-embed-code").html(b.html);a._isLoaded=!0;a._init();a.refreshEmbedCode(!1);$("#embedCodeWP").val(a.wp_code)});window._gaq.push(["_trackEvent","bigfoot_slideview",
"embedtab>open"])};slideshare_object.embed_interaction.prototype.hide=function(){this.visible=!1;$(".j-action-embed").removeClass("current");$(".action-embed-code",slideshare_object.svTools).hide()};slideshare_object.embed_interaction.prototype.toggle=function(){this.visible?this.hide():this.show();return!1};
slideshare_object.embed_interaction.prototype.modeToggle=function(a){this.mode!=a?(this.mode=a,this.mainHeading="wpembed"==a?this.wpHeading:this.embedHeading,$(".j-embed-main-heading",slideshare_object.svTools).html(this.mainHeading),this.show()):this.toggle()};
slideshare_object.embed_interaction.prototype.toggleCustomize=function(){$("#h-customize-embed-section").toggle();this.customizeShown?($(".action-embed-code .h-action-customize").html("Customize&hellip;"),this.customizeShown=!1,window._gaq.push(["_trackEvent","bigfoot_slideview","profile>close"])):($(".action-embed-code .h-action-customize").html("Hide options&hellip;"),this.customizeShown=!0,window._gaq.push(["_trackEvent","bigfoot_slideview","profile>custom"]))};
slideshare_object.embed_interaction.prototype.refreshEmbedCode=function(a){var b=this.embed_sizes,c=this.iframe_code,d=$("#embed-iframe"),g=this.iframe_url,f=$("#embed-customize-withrel").is(":checked")||"0"===slideshare_object.slideshow.show_related_content,e=parseInt($("#embed-customize-slidenumber").val(),10),i=$(".j-embed-size>a>span.j-embed-display.selected").parent("a").attr("id").split("_").pop(),j;j=b.presets[i].size.paddedWidth;b=b.presets[i].size.paddedHeight;i=[];f&&i.push("rel=0");!isNaN(e)&&
1<e&&i.push("startSlide="+e);i.length&&(g+="?"+i.join("&"));c=c.replace(/\{iframe_url\}/g,g);c=c.replace(/\{width\}/g,j);c=c.replace(/\{height\}/g,b);d.val(c);a&&d.is(":visible")&&this._notifyUpdated(this.iframe_clipboard)};
slideshare_object.embed_interaction.prototype.changeEmbedSizeAspectRatio=function(){var a=this.embed_sizes;if("undefined"!==typeof a){var b=player.controller.slideAspectRatio;if(b)for(var c in a.presets)a.presets.hasOwnProperty(c)&&(preset=a.presets[c],preset.size.height=parseInt(preset.size.width*b+49,10))}};slideshare_object.favorites_interaction=function(){this._init()};
slideshare_object.favorites_interaction.prototype._init=function(){$(".j-action-addfav",slideshare_object.svTools).on("click",function(){$(".player").hasClass("fullscreen")&&$.slideshareEventManager&&$.slideshareEventManager.trigger("leavefullscreen");slideshare_object.addAfterLoginEvent({event:"like",data:{slideshow_id:slideshare_object.slideshow.id}})})};slideshare_object.favorites_interaction.prototype.show=function(){this.visible=!0;slideviewInteraction.hideAll("favorites")};
slideshare_object.favorites_interaction.prototype.hide=function(){this.visible=!1};slideshare_object.leads_interaction=function(){this._init()};
slideshare_object.leads_interaction.prototype._init=function(){var a=this,b=".j-download",c=!0,d=slideshare_object.jsplayer,g=d&&d.has_new_lead_form?"new_leadsform":"bigfoot_leadsform";if(slideshare_object.lead){var f=slideshare_object.slideshow?slideshare_object.slideshow.id:-1;window._gaq.push(["_trackEvent",g,"pageload",f]);$("#action-open-lead-section").load(slideshare_object.lead.form_url,function(d,i,j){if(200==j.status){"false"!=$("#for_sidebar").val()&&($(".no-lead").remove(),$(".noAdForLead").remove(),
$("p.embed").addClass("l-embed"),$(".embed-code").addClass("l-embed-code"),$("div.lead-cta-only").show());"false"==$("#for_download").val()&&(c=b=!1,slideshare_object.downloads.sp_isdwnl?$(".j-action-download").show():$(".j-action-download").remove());var h=$("#leadsform-placeholder",this).hide();h.addClass("expandedOverlay");var p=$(".progress",h),w=$(".progress_done",h);h.form=$("form",h);h.form[0]&&(h.form.submit(function(a){a.preventDefault();a.stopPropagation();try{if(h.form[0].validate_formfields()){h.css({height:120});
p.show();h.form.hide();var c=h.hasClass("downloadform"),d=h.hasClass("contactform");c?h.form.evt_trackAjaxOkay(g,"sent-download"):h.form.evt_trackAjaxOkay(g,"sent");$.post(h.form[0].action,"mechanism="+(c?"Download&":d?"Sidebar&":"")+h.form.serialize(),function(a){log(a);w.show();$(".j-close-lead-form").show();$("#leadLogin").toggle();p.hide();setTimeout(function(){slideshare_object.downloads&&slideshare_object.downloads.allow&&b?($("form",h).remove(),$(".progress_done",h).after(a.html),c&&a.download_url&&
(window.location=a.download_url)):h.html('<div class="progress_done">'+w.html()+"</div>")},3500)},"json");slideshare_object.jsplayer&&(player.controller.setLeadFilledForAuthor(),player.controller.currentComponentSet.leadcta&&player.controller.currentComponentSet.leadcta.hide())}}catch(e){window.console&&console.log(e)}}),$("#leadsform-placeholder .action-learnmore").clone().prependTo("#leadAuthor").addClass("outside").addClass("learnMoreTitle"),$("#leadsform-placeholder .offer_text.normal").clone().appendTo("#action-open-lead-section"),
$("#leadsform-placeholder .offer_text.normal").remove(),$(".j-close-lead-form").click(function(b){b.preventDefault();b.stopPropagation();a.hide();slideshare_object.jsplayer&&player.controller.activateToolbar()}),$("#leadAuthor .action-learnmore").click(function(a){a.preventDefault();a.stopPropagation();jQuery("#leadsform-placeholder",slideshare_object.svTools).removeClass("expanded").hide();$(".action-learnmore, "+b).parent().removeClass("current");a=$("#leadsform-placeholder");a.removeClass("expanded").removeClass("downloadform");
a.addClass("contactform").insertAfter("#leadAuthor");a.toggle();$(".leadAuthorImg").toggle();$("#leadLogin").toggle()}),c&&($(".action-learnmore",slideshare_object.svTools).click(function(a){a.preventDefault();a.stopPropagation();$("#action-open-lead-section #leadsform-placeholder").hide();$("#action-open-lead-section .outside").show();jQuery("#leadsform-placeholder.downloadform").removeClass("expanded").hide();$("#leadsform-placeholder").appendTo(".j-tools:first-child").toggle();$(this).parent().toggleClass("current");
$(b,slideshare_object.svTools).parent().removeClass("current");h.css("background-color","").toggleClass("expanded").addClass("contactform").removeClass("downloadform")}),$(b).click(function(c){if(slideshare_object.jsplayer&&player.controller.checkLeadFilledForAuthor())return $("#leadsform-placeholder .skip").click(),!0;$(".leadAuthorImg").show();$("#action-open-lead-section #leadsform-placeholder").hide();$("#action-open-lead-section .outside").show();$("#leadsform-placeholder.contactform").removeClass("expanded").hide();
$("#leadsform-placeholder").appendTo(".j-tools:first-child").toggle();$(b,slideshare_object.svTools).parent().toggleClass("current");$(".action-learnmore",slideshare_object.svTools).parent().removeClass("current");h.css("background-color","").toggleClass("expanded").removeClass("contactform").addClass("downloadform");$("#leadLogin").show();a.show();c.preventDefault();c.stopPropagation()}),"true"===getUrlVar("dl")&&$(b).click()),$(".action-learnmore").click(function(b){b.preventDefault();b.stopPropagation();
a.show()}),$("#leadsform-placeholder .cancel").click(function(a){a.preventDefault();a.stopPropagation();$(b,slideshare_object.svTools).parent().removeClass("current");$(".action-learnmore",slideshare_object.svTools).parent().removeClass("current");$("#action-open-lead-section .action-learnmore").show();h.css("background-color","").removeClass("expanded").hide();slideshare_object.jsplayer&&player.controller.activateToolbar()}),$("#leadsform-placeholder .skip").click(function(a){a.preventDefault();
a.stopPropagation();$(b,slideshare_object.svTools).parent().removeClass("current");$(".action-learnmore",slideshare_object.svTools).parent().removeClass("current");$("#action-open-lead-section .action-learnmore").show();h.css("background-color","").removeClass("expanded").hide();window.location=$(b).data("href")+"&skip=true"}),$(".j-download",slideshare_object.svTools).evt_track(g,"open-download",f),$(".j-track-lead",$(".playerWrapper")).click(function(){window._gaq.push(["_trackEvent",g,$(this).data("ga"),
f])}),$("form",h)[0]&&(window.newform||window.location.href.match(/\?newform/)?($(".action-contactform a").html("Ask a question"),$(".action-contactform",slideshare_object.svTools).show()):$(this).show()),$(b).parent().show(),"false"==$("#for_sidebar").val()&&$("#action-open-lead-section").hide())}else $(".lead-cta-only").remove(),$("#action-open-lead-section").remove(),$(b).parent().show()})}else $(".lead-cta-only").remove(),$("#action-open-lead-section").remove(),$(b).parent().show()};
slideshare_object.leads_interaction.prototype.hide=function(){$("#leadsform-placeholder").hide();slideshare_object.jsplayer&&player.controller.activateToolbar()};slideshare_object.leads_interaction.prototype.show=function(){slideviewInteraction.hideAll("leads");slideshare_object.jsplayer&&(player.controller.isToolbarActive()?player.controller.deactivateToolbar():player.controller.activateToolbar())};
slideshare_object.sharing_interaction=function(){window.share_form_click=function(){$(".j-action-email",slideshare_object.svTools).click()};this._init()};
slideshare_object.sharing_interaction.prototype._init=function(){var a=this;this.share_li=null;$(".j-action-share",slideshare_object.svTools).unbind("click").click(function(){slideviewInteraction.hideAll("msharing");$.slideshareEventManager&&$.slideshareEventManager.trigger("playershare","toolbar_")});$(".j-action-email",slideshare_object.svTools).unbind("click").click(function(b){b.preventDefault();a.load()})};
slideshare_object.sharing_interaction.prototype.load=function(){var a=this;window.location.href.match(/popupshare/)?window.open("/share/"+slideshare_object.presentationId,"ss_share","width=900,height=700,resizable=no,scrollbars=yes,status=0").focus():(a.show(),this.share_li||(this.share_li=$('<li class="expanded action-share-form" style="display:none"><div class="svLightBox">'+slideshare_object.loading_html+"</div></li>").appendTo(slideshare_object.svTools),$.get("/share/contacts/"+slideshare_object.presentationId,
function(b){$(".svLightBox",a.share_li).html(b);try{slideshare_object.track_shareform(a.share_li)}catch(c){}a.share_li.toggleClass("expanded");$("style",a.share_li).appendTo("head");try{setup_shareform(function(){a.share_li.hide();$(".j-action-email",slideshare_object.svTools).removeClass("current")})}catch(d){}})),this.share_li.toggle(),$(".j-action-email",slideshare_object.svTools).toggleClass("current"))};
slideshare_object.sharing_interaction.prototype.hide=function(){this.visible=!1;$(".action-share-form").hide();$(".j-action-email").removeClass("current")};slideshare_object.sharing_interaction.prototype.show=function(){slideviewInteraction.hideAll("sharing");this.visible=!0};function Tabbox(a,b){this.init(a,b)}
Tabbox.prototype={tabbox:null,tabs:[],selected:null,config:{header:"h3",vertical:!1,select:-1,padding:0,autosize:!0},init:function(a,b){function c(){for(var b=document.getElementById(a),e=b;e;){if(e.nextSibling||d.pageLoaded){d.tabbox=b;d.formatTabbox();return}e=b.parentNode}setTimeout(c,25)}var d=this;if(b)for(var g in b)this.config[g]=b[g];this.pageLoaded=!1;window.addEventListener?window.addEventListener("load",function(){d.pageLoaded=!0},!1):window.attachEvent&&window.attachEvent("onload",function(){d.pageLoaded=
!0});c()},formatTabbox:function(){this.tabs=[];this.tabbox.className+=" tabbox";this.tabbox.className=this.config.vertical?this.tabbox.className+" verticalTabs":this.tabbox.className+" horzTabs";for(var a,b=this.tabbox.getElementsByTagName(this.config.header),c=0;c<b.length;c++){this.tabs[c]={id:b[c].id,header:b[c],container:b[c].parentNode};a=this.tabs[c].container.getElementsByTagName("div");for(var d=0;d<a.length;d++)if(a[d].className.match(/(^|\s)tabContent(\s|$)/)){this.tabs[c].id=a[d].id;this.tabs[c].content=
a[d];break}}b=function(a,b){return function(c){c=window.event||c;b.selectTab(a,c)}};for(c=0;c<this.tabs.length;c++)a=this.tabs[c].container.getElementsByTagName("a"),0<a.length&&(a=a[0],a.tab=this.tabs[c],a.onfocus=b(a.tab,this),a.onclick=b(a.tab,this));this.getSelected();"undefined"!=typeof this.config.select&&this.selectTab(this.config.select);this.adjustFootprint()},selectTab:function(a,b){b&&(b.preventDefault?b.preventDefault():b.returnValue=!1);isNaN(a)?"string"==typeof a&&(a=this.getTabById(a)):
a=this.tabs[parseInt(a,10)];a&&(this.selected&&(this.selected.container.className=this.selected.container.className.replace(/selected/g,"")),a.container.className+=" selected",this.selected=a,this.adjustFootprint())},getTabById:function(a){for(var b=0;b<this.tabs.length;b++)if(this.tabs[b].id==a)return this.tabs[b];return null},getSelected:function(){for(var a=0;a<this.tabs.length;a++)if(this.tabs[a].container.className.match(/(^|\s)selected(\s|$)/))return this.selected=this.tabs[a],a},adjustFootprint:function(){if(!1!==
this.config.autosize&&this.selected){var a=this.selected.content.clientHeight+5;!1===this.config.vertical&&(a+=this.selected.header.clientHeight);this.tabbox.style.height=a+"px"}}};slideshare_object.toggleSiblings=function(a,b,c,d){$(a).show();$(b).hide();$(c).show();$(d).hide()};slideshare_object.setupDescriptionBoxToggle=function(){$(".j-desc-more").click(function(a){a.preventDefault();$(this).hide();$(".j-desc-expand").show();$(".thumbnailGrid").trigger("adjustHeight")})};
slideshare_object.slideviewInteraction=function(){this.slideviewInteractionObjects={};this.slideviewInteractionObjects.favorites=new slideshare_object.favorites_interaction;this.slideviewInteractionObjects.sharing=new slideshare_object.sharing_interaction;this.slideviewInteractionObjects.download=new slideshare_object.download_interaction;this.slideviewInteractionObjects.leads=new slideshare_object.leads_interaction;this.slideviewInteractionObjects.embed=new slideshare_object.embed_interaction({allow_embeds:slideshare_object.slideshow.allow_embeds,
embed_sizes:slideshare_object.slideshow.embed_sizes,wp_code:slideshare_object.slideshow.wp_code,iframe_code:slideshare_object.slideshow.iframe_code,iframe_url:slideshare_object.slideshow.iframe_url,slideshow_type:slideshare_object.slideshow.type,zeroclipboard_url:slideshare_object.slideshow.zeroclipboard_url})};
slideshare_object.slideviewInteraction.prototype.hideAll=function(a){for(var b in this.slideviewInteractionObjects)this.slideviewInteractionObjects.hasOwnProperty(b)&&b!==a&&this.slideviewInteractionObjects[b].hide();"msharing"!==a&&$(".modal-share").is(":visible")&&$.slideshareEventManager&&$.slideshareEventManager.trigger("playershare")};
$(function(){function a(a,b){$(b).length&&$(b).wrap("<li/>").parent().prependTo($(a))}var b=!1;a("#relatedList",".j-removeRelatedCTA");$(".j-more-slideshows").length&&a("#moreList",".follow-in-sidebar");slideshare_object.svComments=$(".commentsNotes");slideshare_object.svCommentsForm=$("form.j-comment-post");slideshare_object.svCommentsul=$("#commentsList");slideshare_object.svTools=$(".j-tools");slideshare_object.setup_instruments_interaction&&slideshare_object.setup_instruments_interaction();slideshare_object.setupDescriptionBoxToggle();
$(".logo").click(function(a){a.preventDefault();window.location.href="/"});$(".j-more-slideshows").length&&0===$(".j-related-slideshows").length&&($(".j-more-slideshows").toggleClass("active"),$("#moreList").toggleClass("activeContent").toggle(),slideshare_object.toggleSiblings(".j-more-slideshows",null,".moreContent",null));$("#downloadsList").length&&0===$(".j-favs-list").length&&($("#downloadsList").attr("style","display: block; "),$(".j-downloads-tab").toggleClass("active"));$(".j-text-version").click(function(a){a.preventDefault();
$.scrollTo($(this).attr("href"),500,{offset:-40});window._gaq.push(["_trackEvent","bigfoot_slideview","scroll_to_transcript"])});$(".j-post-comment").click(function(a){a.preventDefault();$.scrollTo($(this).attr("href"),500,{offset:-50});$(".j-post-comment-textarea").focus()});$(".slideshow-tags a:gt(4)").hide();$(".j-more-tags").click(function(a){a.preventDefault();"More..."===$(this).text()?($(this).text("...less"),$(".slideshow-tags a:gt(4)").show()):($(this).text("More..."),$(".slideshow-tags a:gt(4)").hide())});
$(".j-transcripts>li").each(function(){""===$(this).html()&&!$(this).hasClass("noTranscript")&&$(this).addClass("empty")});$.each([{tabToShow:".j-more-slideshows",tabToHide:".j-related-slideshows, .j-trending",contentToShow:".moreContent",contentToHide:".relatedContent, #activityList, .li-network-content-title, #ss-trending",addScrollBar:"#moreList",callback:function(){$(".thumbnailGrid").trigger("adjustHeight");$(window).trigger("scroll")}},{tabToShow:".j-related-slideshows",tabToHide:".j-more-slideshows, .j-trending",
contentToShow:".relatedContent , .li-network-content-title",contentToHide:".moreContent , #activityList, #ss-trending",callback:function(){$(".thumbnailGrid").trigger("adjustHeight");$(window).trigger("scroll")}},{tabToShow:".j-trending",tabToHide:".j-more-slideshows, .j-related-slideshows",contentToShow:"#ss-trending",contentToHide:".moreContent , #activityList, .relatedContent",callback:function(){$(".thumbnailGrid").trigger("adjustHeight")}},{tabToShow:".j-comments",tabToHide:".j-notes, .j-favorites, .j-stats, .j-downloads",
contentToShow:".commentsWrapper",contentToHide:".notesWrapper, .favWrapper, #stats-container, .downloadWrapper",callback:function(){$(".thumbnailGrid").trigger("adjustHeight")}},{tabToShow:".j-notes",tabToHide:".j-comments, .j-favorites, .j-stats, .j-downloads",contentToShow:".notesWrapper",contentToHide:".commentsWrapper, .favWrapper, #stats-container, .downloadWrapper",callback:function(){$(".thumbnailGrid").trigger("adjustHeight")}},{tabToShow:".j-favorites",tabToHide:".j-notes, .j-comments, .j-stats, .j-downloads",
contentToShow:".favWrapper",contentToHide:".notesWrapper, .commentsWrapper, #stats-container, .downloadWrapper",callback:function(){$(".thumbnailGrid").trigger("adjustHeight")}},{tabToShow:".j-stats",tabToHide:".j-notes, .j-comments, .j-favorites, .j-downloads",contentToShow:"#stats-container",contentToHide:".notesWrapper, .commentsWrapper, .favWrapper, .downloadWrapper",callback:function(){if(!b){b=!0;var a={id:slideshare_object.slideshow.id};slideshare_object.analytics_api_enabled&&$.ajax({type:"GET",
url:"/slideshow/stats",data:a,dataType:"json",success:function(a){var b=$(".j-info-embeds"),c=b.find(".j-embed-details");$(".j-slideshare-views").text(a.slideshow_analytics_on_ss);$(".j-embed-views").text(a.slideshow_analytics_views_from_embeds);if(0<a.slideshow_analytics_top_embeds.length){for(var e=0;e<a.slideshow_analytics_top_embeds.length;e++){var i=a.slideshow_analytics_top_embeds[e];c.append('<tr><td class="url">'+i.url+'</td><td class="count">'+i.hits+"</td></tr>")}b.find(".j-no-embeds").remove();
c.show()}}})}$(".thumbnailGrid").trigger("adjustHeight")}},{tabToShow:".j-downloads",tabToHide:".j-notes, .j-comments, .j-favorites, .j-stats",contentToShow:".downloadWrapper",contentToHide:".notesWrapper, .commentsWrapper, #stats-container, .favWrapper",callback:function(){$(".thumbnailGrid").trigger("adjustHeight")}}],function(a,b){$(b.tabToShow).bind("click",function(a){a.preventDefault();$(b.tabToHide).removeClass("active");$(b.tabToShow).addClass("active");$(b.contentToShow).addClass("activeContent");
$(b.contentToHide).removeClass("activeContent");slideshare_object.toggleSiblings(null,null,b.contentToShow,b.contentToHide);b.callback&&b.callback.call(b)})});slideshare_object.user.loggedin?(ssComments=new SSCommentsLoggedIn(slideshare_object),ssSuperUser=new SSSuperUserActions(slideshare_object)):ssComments=new SSComments(slideshare_object);ssContactsFollow=new SSContactsFollow(slideshare_object);slideshare_object.setup_activitylist_interaction();slideshare_object.setup_fbconnect_interaction&&(slideshare_object.setup_fbconnect_interaction(),
slideshare_object.setup_opengraph_interaction());slideshare_object.setup_flagging_interaction();slideshare_object.bindToModalLogin(".j-action-addfav a");slideshare_object.bindToModalLogin(".j-download");slideshare_object.ready();window.slideviewInteraction=new slideshare_object.slideviewInteraction});
